### ISSUE TITLE
(x)screensaver doesn't stop when monitor backlight turns off

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-screensaver#100]
Cinnamon 2.6.7, LM 17.1 64 bit
I don't know if it's a regression, but since xscreensaver is "new" in Cinnamon...
Set screensaver to 5 minutes, turn monitor off after 15 minutes. Fans begin to turn faster because of the screensaver raising temperature (ok), but still run fast the whole time after the screen turns black.
It would be better to stop the grafic calculation because it's not needed.

**Comment by JosephMcc** [comment]
Xscrensaver support is gone and no longer supported.
