### ISSUE TITLE
Confusing cinnamon-screensaver 2.6 options

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon-screensaver#103]
Hello, the 2.6 release of cinnamon-screensaver has confusing options that don't seem to do what I would expect:

![screenshot from 2015-06-25 15 02 29](https://cloud.githubusercontent.com/assets/2692138/8364422/ca5bc51c-1b4b-11e5-9d21-1e4fb29ee581.png)

I was looking for an option to control the delay before my screensaver turns on (and before my monitor powers off) but I don't want my screen to lock. Now that Cinnamon has actual screensavers, I believe the label of the "Lock the computer when inactive" toggle isn't really correct. As I tested it, it appears to be the time before the screensaver kicks in. In some cases, the screensaver could actually be a blank screen with the current time if the "Screen Locker" screensaver is selected (also confusing) but there's no actual locking involved when using the options I show in my screenshot.

**Comment by marga-debian** [comment]
In the current cinnamon-screensaver (3.0) there are now two different options:

- Delay before locking the screen (This option defines the amount of time to wait before locking the screen, after showing the screensaver or after turning off the screen)->underlying setting is lock-delay

- Lock the computer when inactive (This option defines the amount of time to wait before locking the screen, when the computer is not being used) -> underlying setting is idle-delay

This seems even **more** confusing.

To check the behavior, I set idle-delay to 1 minute and lock-delay to 1 hour and the effect I got was that after a minute the screensaver got activated, but the screen was not locked.

I think that the description of idle-delay should be changed to:
Start the screensaver when inactive (This option defines the amount of time to wait before starting the screensaver, when the computer is not being used)

Additionally, as @geckolinux says, it should be possible to start the screensaver and not lock the screen.  Why is there a "Never" option for idle-delay but not for lock-delay?

**Comment by marga-debian** [comment]
Actually, the "Never" option I was asking for is what is shown in the screenshot, i.e. turning the "Lock the computer when screen turn off" button to off means that the computer is never locked.  This is clarified in the explanation of the setting, but at first sight it does seem that the setting is only about turning off, not screensaver activation.
