### ISSUE TITLE
Configuration options or saner defaults for xscreensaver screensavers?

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/cinnamon-screensaver#105]
Hi there,

Very nice to see that Cinnamon has real screensavers available now. But would it be possible to make them configurable? Or at the very least could some saner defaults be used? For example in the ones where it destroys or distorts the current screen image, it should be configured by default to actually act on the screen image and not on that ugly default color-pallete style picture.

Thanks a lot!

**Comment by rickrich** [comment]
I agree.  You should add 'xscreensaver-hack-args' to the gsettings.

Example:
$ gsettings get org.cinnamon.desktop.screensaver xscreensaver-hack
'glslideshow'

$ gsettings set org.cinnamon.desktop.screensaver xscreensaver-hack-args '-duration 10 -pan 10'

**Comment by mrbrahman** [comment]
Assuming I use only the glslideshow screensaver, is there is work-around for now to enable duration and pan?

I really like the Cinnamon login (rather than xscreensaver login), and hence trying to find some temporary workaround.

FYI - I tried adding the line 44 below to `/usr/share/cinnamon-screensaver/screensavers/xscreensaver@cinnamon.org/main`

```
39     for direc in directories:
40         try:
41             path = shlex.split(direc + hack)
42             path.append("-window-id")
43             path.append(xid)
44             path.append(" -duration 20 -pan 20 -fade 3 -titles")
```
But that did not seem to help. It was instead showing me a white screen :-(

**Comment by mrbrahman** [comment]
Nevermind... Realized I had to add those as individual parameters :-)
```
39     for direc in directories:
40         try:
41             path = shlex.split(direc + hack)
42             path.append("-window-id")
43             path.append(xid)
44             path.append("-duration")
45             path.append("20")
46             path.append("-pan")
47             path.append("20")
48             path.append("-fade")
49             path.append("3")
50             path.append("-titles")
```
Can live with this workaround for now until a clean solution is implemented.

**Comment by sirg** [comment]
`gsettings set org.cinnamon.desktop.screensaver xscreensaver-hack 'glslideshow -titles'`
works for me.

**Comment by JosephMcc** [comment]
Xscrensaver support is gone and no longer supported.

**Comment by mrbrahman** [comment]
@JosephMcc - do you mean it is no longer supported in the version 19? I haven't installed that version yet, but just wanted to find out if something like glslideshow is supported at all?

**Comment by JosephMcc** [comment]
In Mint19.1 and Cinnamon 4.0 the xscreensaver stuff is gone.

**Comment by rickrich** [comment]
Wow, glslideshow is my #1 screensaver.  Used it for at least 15 years.  I guess I'll look at Gnome instead of Cinnamon 4.0.

**Comment by clefebvre** [comment]
Afaik only mate-screensaver and xscreensaver itself support these hacks. There are reasons this is going, it's not maintainable long-term and it causes security issues and rendering issues we're unable to solve.

**Comment by rickrich** [comment]
Cinnamon Settings -> Screensaver -> Delay before starting screensaver -> Never
Cinnamon Settings -> Startup Applications -> Add -> Name -> Xscreensaver
Cinnamon Settings -> Startup Applications -> Add -> Command -> xscreensaver
Cinnamon Settings -> Startup Applications -> Add -> Save

logout
login

**Comment by mtwebster** [comment]
Good for you
