### ISSUE TITLE
"Bumps" screensaver resource hogging

### ISSUE THREAD

**Issue by bbbco** [linuxmint/cinnamon-screensaver#107]
I recently upgraded to Cinnamon 2.6.8 with the support for Gnome screensavers. I went ahead and selected the screensaver "Bumps" to start using.

I left my desktop over the weekend, and when I came back, it took me a while to log in. After logging back in, I noticed that my resource usage was extremely high (RAM all used up, mostly into swap, etc). I noticed that the "bumps" processes were still running even after unlocking the desktop:

```
bbbco    13644  3.0 15.8 3521332 1269156 ?     S    Jul10 116:20 /usr/lib/xscreensaver/bumps -window-id 67108867
bbbco    13645  2.6 15.5 3338368 1249012 ?     S    Jul10 102:34 /usr/lib/xscreensaver/bumps -window-id 69206019
```

Killing these processes freed up half of my RAM and most of the swap. Seems like there is a leak somewhere.

**Comment by bbbco** [comment]
I'm guessing this could happen from screensaver to screensaver. I'm gonna try different screensavers and see if I experience the same issue.

**Comment by pizzadude** [comment]
This happens to me with the helios screensaver (from the rss-glx package).

**Comment by leigh123linux** [comment]
You will need to file your issue against xscreensaver.
