### ISSUE TITLE
Dark text on login window

### ISSUE THREAD

**Issue by boingo-00** [linuxmint/cinnamon-screensaver#117]
Username merges with window in dark themes. Fix this
![img_20160321_163950](https://cloud.githubusercontent.com/assets/10793815/13920437/70903174-ef8c-11e5-9b48-2d528b70e569.jpg)

**Comment by JosephMcc** [comment]
This should fix the issue: https://github.com/linuxmint/cinnamon-screensaver/pull/122

**Comment by JosephMcc** [comment]
The fix is now merged.
