### ISSUE TITLE
Screen lock background hidden

### ISSUE THREAD

**Issue by rpbaptist** [linuxmint/cinnamon-screensaver#118]
I am guessing this is the cause of the overlay not being transparant somehow:

Sorry for the bad image, I was unable to make a screenshot while locking.

![img_20160323_211636](https://cloud.githubusercontent.com/assets/7916262/13999466/b9acf52a-f13c-11e5-8798-9de2104b5335.jpg)

**Comment by boingo-00** [comment]
Try to change/update theme

**Comment by rpbaptist** [comment]
Thanks, that was exactly it. Not sure why it broke though.

**Comment by rpbaptist** [comment]
Do you have any idea which setting may be responsible for this? The same theme was working for me fine in Linux Mint.

**Comment by rpbaptist** [comment]
Nevermind, I removed a so-called fix with the Numix based theme and it solved it.
