### ISSUE TITLE
Lock screen doesnt test for capslock being on when shown

### ISSUE THREAD

**Issue by philipzae** [linuxmint/cinnamon-screensaver#120]
Steps:
1) activate capslock
2) activate the lock screen
3) move mouse or press a key to show lock screen password dialog
4) the message 'You got caps lock key on' doesnt appear under the password field
5) press capslock until the message 'You got caps lock key on' does appear
6) wait till the lock screen password dialog disappears
7) move mouse or press a key to show the dialog
8) the message 'You got caps lock key on' doesnt appear under the password field

this problem has caused me alot of problems, as i would be typing in the password correctly and it wouldnt go through and there was no indication that capslock was on. so the best/simplest solution would be to disable capslock when the lock screen password dialog appears.

**Comment by monsta** [comment]
Sounds similar to https://github.com/mate-desktop/mate-screensaver/issues/81?

**Comment by mtwebster** [comment]
I can't reproduce this.

It checks here when showing the dialog: https://github.com/linuxmint/cinnamon-screensaver/blob/master/src/gs-lock-plug.c#L939

Maybe some sort of race condition interacting with gtklock/plug

**Comment by monsta** [comment]
Now that you mention it, I can't reproduce it in Cinnamon 3.0 in Betsy as well. Maybe it was a problem in 2.8.

**Comment by JosephMcc** [comment]
The new screensaver very clearly shows when CapsLock in enabled.
