### ISSUE TITLE
Control bar of VLC (playbar at the bottom of the screen) still show up in full screen 

### ISSUE THREAD

**Issue by f380cedric** [linuxmint/cinnamon-screensaver#121]
The control bar of VLC (when full screen) is still show up when cinnamon is on screensaver.

Steps:

1. Open a media with VLC
2. Press F for full screen mode of VLC
3. Place your mouse on the control bar (bar at the bottom of the screen)
4. Lock cinnamon (shortcut Ctrl + Alt + L)

Versions:
- Linux Mint 17.3 Rosa
- VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)
- Cinnamon 2.8.8
- Cinnamon-screensaver 2.8.0

**Comment by feren** [comment]
Can't reproduce it here in Cinnamon 3.0.7 DEV in Linux Mint 18, seems they fixed it in 3.X

**Comment by f380cedric** [comment]
That's true, I will close :)
