### ISSUE TITLE
Make webkit optional.

### ISSUE THREAD

**Issue by SparkyBluefang** [linuxmint/cinnamon-screensaver#125]
In source based distros like Gentoo, building webkit takes a long time. It would be nice if it were an optional dependency, especially if the end user is only intending to use xscreensaver hacks.

Downstream bug: https://bugs.gentoo.org/show_bug.cgi?id=560764

**Comment by mtwebster** [comment]
In the development version of cinnamon-screensaver, it's been ported mostly to python, and, at least in the debian/ubuntu packaging, I've made a cinnamon-screensaver-x-plugin and cinnamon-screensaver-webkit-plugin, each of which have their own runtime dependencies (including webkit, etc...)

I don't know how or if that affects you in Gentoo.. but this makes it for us basically that the webkit and xscreensaver stuff is completely optional (the core program requires neither).
