### ISSUE TITLE
Support of glslideshow parameters

### ISSUE THREAD

**Issue by mrbrahman** [linuxmint/cinnamon-screensaver#131]
xscreensaver **glslideshow** hack accepts a bunch of useful parameters to control the **duration**, **pan**, **fade** and **titles** of the Pictures being shown. 

I haven't found a way to enable those from cinnamon-screensaver (UI or otherwise). I tried changing the below files, but that didn't take effect.

.xscreensaver 
/etc/X11/app-defaults/XScreenSaver-gl
/usr/share/applications/screensavers/glslideshow.desktop

Can someone help?

Thanks!

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/105
