### ISSUE TITLE
[Feature Request] Add reboot notification to lockscreen

### ISSUE THREAD

**Issue by gerow** [linuxmint/cinnamon-screensaver#142]
This seems a reasonable place to let the user know they have installed packages that might want a reboot; quote from one of our users:

> It would be better to show this message when I'm done for the day. That way, I don't lose time waiting for the reboot. One way to accomplish this might be to show the reboot-needed message at the lock screen.

The screensaver could just check /var/run/reboot-required and display an appropriate message.

This is very much a nice-to-have for us, I'm mostly interested in if cinnamon devs think this is a sensible approach.

**Comment by JosephMcc** [comment]
Currently in Mint we don't show reboot required messages at all. The new screensaver coming in Cinnamon 3.2 will show when you have new notifications but not the content of them. Will that meet your needs? If you're distro gives a notification that a reboot is required, it should show there. I don't think it is persistent once you unlock the screen though.

**Comment by gerow** [comment]
> I don't think it is persistent once you unlock the screen though.

I think that's the issue, then; a lot of users will see the reboot notification and think "oh, I'll do that later" and then forget about it because they're in the middle of something. Whereas when a user locks their screen they're probably more likely to think "oh, I was just going to step away from my machine, but I guess I could reboot while I'm stepping away too".

In this case a persistent message on the lockscreen saying something like "Reboot recommended" might be nice; doesn't have to be (and probably shouldn't be) something loud and in your face.

**Comment by mtwebster** [comment]
I think this would be better off being done by the update manager (if you need to reboot, its icon changes to something reboot-ish.. I'm not sure the desktop should have to involve itself here (This way the implementation works with other desktops as well)

**Comment by leigh123linux** [comment]
-1 for this stupid idea.

**Comment by gerow** [comment]
@mtwebster Perhaps, we can close this out for now. I might try adding it to our fork of the screensaver and see if I can gather some data on how it affects how often our users reboot. Really, getting people to reboot more proactively is all we're trying to do.

@leigh123linux your snark is totally unnecessary here.

**Comment by leigh123linux** [comment]
@gerow  I'm entitled to express my opinion, adding any 'power off' or 'reboot' stuff to the lock screen is unacceptable as other users may be logged in.
As for your comment, grow up and accept the idea was poor instead of criticizing me for my valid opinion!
