### ISSUE TITLE
[Feature Request] Unlock cinnamon-screensaver automatically on LightDM login

### ISSUE THREAD

**Issue by hleblanc** [linuxmint/cinnamon-screensaver#144]
Hello everybody! On my Debian system I use Cinnamon together with LightDM, and if cinnamon-screensaver locks the screen, and I press "switch user", if I want to log in back as my main user, I type my login/password in LightDM, but I still have to type my password again in cinnamon-screensaver after LightDM login. Is it possible to make cinnamon-screensaver automatically unlock user's session, if he logins using LightDM? That would be great.

**Comment by lots0logs** [comment]
This seems to have been fixed. It works for me with latest version of cinnamon-screensaver and lightdm-1.18.3

**Comment by JosephMcc** [comment]
@hleblanc Can you confirm this works for you? You never bothered to mention the versions of anything you are running.

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/95e62f05ceb276d83f3aeff4359f3e4d18002a12
