### ISSUE TITLE
Fingerprint auth is broken since 3.2.0

### ISSUE THREAD

**Issue by UntilSunrise** [linuxmint/cinnamon-screensaver#147]
Since the update to 3.2.0 i cant unlock via fingerprint. The auth code is started if i enter a password and hit enter but this is to late, the  pam_fprint.so line will be bypassed.

/etc/pam.d/system-auth :

 auth       required pam_env.so
 auth       sufficient   pam_fprintd.so
 auth       sufficient   pam_unix.so try_first_pass likeauth nullok
 auth       required pam_deny.so

**Comment by mtwebster** [comment]
Can you suggest brand of scanner or are you using a built-in one (like on a Lenovo laptop)?  I'll buy one to fix this issue, I just want to be sure it's compatible with Linux (not sure if this is common or not)

**Comment by UntilSunrise** [comment]
I am using the build in one from my Thinkpad T430

**Comment by mtwebster** [comment]
Ok I just ordered a Lenovo keyboard, we'll get this figured out.

**Comment by mtwebster** [comment]
Also, what distro are you using?  Thanks

**Comment by UntilSunrise** [comment]
I am using arch linux

**Comment by UntilSunrise** [comment]
To clarify the exact problem.
The prompt to use the fingerprint-scanner should be triggered when the login prompt is shown. Currently the fingerprint prompt is shown if i enter at least a char (dont have to be the right password) into the password field and hit enter.

**Comment by nipperv** [comment]
And the bug is closed in both trackers.

**Comment by mtwebster** [comment]
Fixed by 38a626d1a3c64736f
