### ISSUE TITLE
Bug in showing artist infomation in player control

### ISSUE THREAD

**Issue by lxhillwind** [linuxmint/cinnamon-screensaver#149]
In file "src/dbusdepot/mediaPlayerWatcher.py", the method of getting 'artist' infomation may not be suitable. For example, if the music player sends 'artist' info to dbus using dbus type String (s) instead of List of Strings (as), cinnamon-screensaver will set 'artist_name' the first letter of the 'artist' info.

**Comment by lxhillwind** [comment]
Pull request here: [#150](https://github.com/linuxmint/cinnamon-screensaver/pull/150).

**Comment by lxhillwind** [comment]
Bug is still here. I can't fix it.

Some additional info: I'm using Arch Linux x86_64, cinnamon 3.2.1-4, cinnamon-screensaver 3.2.0-2

**Comment by mtwebster** [comment]
Should be fixed by 2d6663808dafa50a809 - Could you tell me what player was sending non-standard info?  I'd like to confirm this.

**Comment by lxhillwind** [comment]
I have tested with this commit, and it works. Thank you for your working.

The player is named 'netease-cloud-music', which can be installed via repo [archlinuxcn] easily if you use Archlinux. But it only provides Simplified Chinese.
