### ISSUE TITLE
Can't switch to user without password

### ISSUE THREAD

**Issue by dalcde** [linuxmint/cinnamon-screensaver#15]
https://github.com/linuxmint/Cinnamon/issues/1721

OS: Linux Mint 14 Nadia
Interface: Cinnamon 1.6
Reproduceable: Yes

Ways to reproduce the issue:
1. Lock the screen of my primary user
2. Press on the 'switch user' button
3. Type in the username of my second account (note: this account has no password)

Cinnamon requests a password, but the second account has no password. If I simply press [RETURN] as password, it is rejected.
Accounts with passwords seem to work fine.

**Comment by leigh123linux** [comment]
@dalcde Shouldn't this be filed against mdm?
