### ISSUE TITLE
Can't authenticate user without root privileges. 

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-screensaver#151]
cinnamon-screensaver uses desktop_check_user_password() function from cinnamon-desktop to authenticate user. But this function uses PAM and it doesn't work without root privileges on my system. But if you execute cinnamon-screensaver under root it expects root credentials in unlock dialog.

Can anyone help me and describe how it is expected to work? Thanks!

**Comment by mtwebster** [comment]
You'll need this file: https://github.com/linuxmint/cinnamon-desktop/blob/master/data/cinnamon-desktop installed in /etc/pam.d

Depending on what distro you're on, it may need to have different content than what that particular one has (it's expected generally for the distro maintainer to handle packaging the correct file).

If you're not sure, the equivalent file that was shipped in cinnamon-screensaver 3.0 for your distro should still work here - just rename it to cinnamon-desktop.

**Comment by vladimir-didenko** [comment]
> You'll need this file: https://github.com/linuxmint/cinnamon-desktop/blob/master/data/cinnamon-desktop installed in /etc/pam.d

It is installed. But it doesn't eliminate requirements for root privileges.  Previously I used suid bit to run cinnamon-screensaver under root and it was able to determine current user. With new version this approach doesn't work. Suid bit is not option anymore since cinnamon-screensaver is script now. But it is not big problem and can be solved via polkit. But when running under root new version (as I said previous version worked) is not able to determine current user and expects root password.

**Comment by vladimir-didenko** [comment]
Oh, sorry. It looks like I have found problem on my side. Root privileges are not required on my distro. Process should belong to specific group.

**Comment by vladimir-didenko** [comment]
Sorry but it is still problem. Unfortunately there is no easy way to run GTK program under setgid 

http://www.gtk.org/setuid.html

Previous version of cinnamon-screensaver used special code to bypass it - see setuid.c module. New version doesn't have it.

**Comment by vladimir-didenko** [comment]
For my package I created special tool based on setuid.c

http://git.altlinux.org/people/cow/packages/?p=cinnamon-screensaver.git;a=blob;f=cinnamon-screensaver-runner.c;h=128f19c8e38642de5c78125bb8ecbf7bec845679;hb=HEAD

It spawns actual cinnamon-screensaver implementation. 

Probably we can close this issue though my opinion is that vanilla code also should handle case when PAM authentication requires additional privileges.

**Comment by mtwebster** [comment]
Can you try git master?  I've done an implementation of the original setuid code: https://github.com/linuxmint/cinnamon-screensaver/commit/70c26f88302c5ca8ae2499d191aa800262dc5c40

Unfortunately it's difficult to test all of it on my distro, I'd appreciate some feedback - I'm not 100% it works as is, it may be necessary to have the hack_uid stuff run in front of the python instead of from it.

**Comment by vladimir-didenko** [comment]
@mtwebster  Thank you for all your assistance! Unfortunately GTK checks that process running setuid/setgid bit to early. Actually follow import

```python
from gi.repository import CScreensaver
```
already triggers this check in GTK and it prints follow error message and terminates program

```
(cinnamon-screensaver-main.py:15245): Gtk-WARNING **: This process is currently running setuid or setgid.
This is not a supported use of GTK+. You must create a helper
program instead. For further details, see:

    http://www.gtk.org/setuid.html

Refusing to initialize GTK+.
```

And one another thing. On my system process that should check password via PAM should belong to special 'chkpwd' group. The easiest way to do it is to use sgid bit on /usr/bin/cinnamon-screensaver. But now it is shell script and setgid works only with binaries. So I still need to create small binary that launches main script.

Probably both issues above can be solved the same way - replace current launcher shell script by binary that does all magic with suid/sgid and then launches main Python script.

**Comment by mtwebster** [comment]
Can you test master out again?

https://github.com/linuxmint/cinnamon-screensaver/commit/24c9403c0abf873b548d434ffcff8f5d9c3878d9

**Comment by vladimir-didenko** [comment]
With this version cinnamon-screensaver prints follow error message on start
```
couldn't setgroups to cow (500): Operation not permitted
```

I found that new version of setuid.c differs from old version. I reverted this module to older version from 3.0

http://git.altlinux.org/people/cow/packages/?p=cinnamon-screensaver.git;a=commitdiff;h=7cc852b160b99f8f5ac963fb600e0349fa210e6c

and now it works.

Also I have some questions about check_password_thread() functions from cinnamon-desktop

https://github.com/linuxmint/cinnamon-desktop/blob/master/libcinnamon-desktop/gnome-desktop-utils.c#L364

Question 1. cinnamon-screensaver calls pam_acct_mgmt() function and checks returned value. Unfortunately in my distro this function returns PAM_AUTH_ERR error (don't know specific reason but probably it is rights problem). Old (3.0) version of cinnamon-screensaver ignored returned value with follow comment
```C
/* We don't actually care if the account modules fail or succeed,
 * but we need to run them anyway because certain pam modules
 * depend on side effects of the account modules getting run.
 */
```
I also checked code of xscreensaver and it has more detailed explanation
```C
/* On most systems, it doesn't matter whether the account modules
    are run, or whether they fail or succeed.

    On some systems, the account modules fail, because they were
    never configured properly, but it's necessary to run them anyway
    because certain PAM modules depend on side effects of the account
    modules having been run.

    And on still other systems, the account modules are actually
    used, and failures in them should be considered to be true!

    So:
      - We run the account modules on all systems.
      - Whether we ignore them is a configure option.

       It's all kind of a mess.
    */
```
So my first question - is it possible to add configure option to cinnamon-desktop that will allow to ignore returned value of pam_acct_mgmt()?

Question 2. In previous version of cinnamon-screensaver and in xscrreensaver code there is call of pam_setcred() function
```C
      /* Each time we successfully authenticate, refresh credentials,
         for Kerberos/AFS/DCE/etc.  If this fails, just ignore that
         failure and blunder along; it shouldn't matter.

         Note: this used to be PAM_REFRESH_CRED instead of
         PAM_REINITIALIZE_CRED, but Jason Heiss <jheiss@ee.washington.edu>
         says that the Linux PAM library ignores that one, and only refreshes
         credentials when using PAM_REINITIALIZE_CRED.
       */
      status2 = pam_setcred (pamh, PAM_REINITIALIZE_CRED);
```
In new version of cinnamon-screensaver this call is missed. Was it done intentionally and this call is not really required?

**Comment by mtwebster** [comment]
The setuid.c file is exactly the same as it was in 3.0... was there a patched version for your distro that was being used?

Questions 1 and 2, I found the pam stuff somewhere else - the whole point of rewriting the screensaver was to simplify as much as possible, and I found a tidier version of this code out in the wild and used it.  Trying to get rid of code rot obviously I got rid of a bit of knowledge unfortunately as well.  I'm pretty much fine with adding whatever is needed to setuid.c for your situation to be resolved - this whole thing is a non-issue in the more 'mainstream' distros as far as I know.

As for the actual password code in cinnamon-desktop - I'm ok making those changes you mention - if you can make a PR for it or just link a diff for it, I'll test it on my end and merge it.

I'm tempted to move the password check stuff back into cinnamon-screensaver again.  I put it in -desktop in order to make it accessible elsewhere in the cinnamon universe for any future needs, but I was clearly ignorant of some of the requirements here.  I'd be better off creating something using polkit to do that.

**Comment by vladimir-didenko** [comment]
>The setuid.c file is exactly the same as it was in 3.0... was there a patched version for your distro that was being used?

Oh, sorry. Actually it was patch ported 3 years ago from gnome-screensaver package. So let left current code of suid.c as is. At least it worked previously on many mainstream distros and my patch probably can break it. It is not big problem for me to maintain this small change.

>As for the actual password code in cinnamon-desktop - I'm ok making those changes you mention - if you can make a PR for it or just link a diff for it, I'll test it on my end and merge it.

Ok, I will create PR for it.

**Comment by vladimir-didenko** [comment]
I think we can close this issue.

**Comment by mtwebster** [comment]
I've been meaning to mention, If you want, we can add a configure switch to the build, and #ifdef the setuid.c changes, so at a compatible build for you is possible from the same source as everyone else.

**Comment by vladimir-didenko** [comment]
It will be great! Thank you!

**Comment by mtwebster** [comment]
@vladimir-didenko have a look at changes I made today please - I've removed the pam stuff from cinnamon-desktop and put it all back in cinnamon-screensaver.  Some major issues needed addressed, and it made much more sense to keep it all together... sorry about any extra packaging effort this might entail.

The new code re-uses all of the core pam stuff from 3.0 of the screensaver, with a small helper program to interface with it - and this helper program is what needs setuid now, not the screensaver program itself (I removed its C wrapper)

I also added an `--enable-setres` build option, that will incorporate this patch on demand: http://git.altlinux.org/people/cow/packages/?p=cinnamon-screensaver.git;a=commitdiff;h=7cc852b160b99f8f5ac963fb600e0349fa210e6c

Please let me know if you have any issues.

**Comment by vladimir-didenko** [comment]
@mtwebster  It works! Thank you! There is one small issue though - cinnamon-screensaver-pam-helper is installed to /usr/share/cinnamon-screensaver directory. My distro policy forbids ELF binaries in /usr/share. So I patched package. Probably is better to move this binary to some other location (e.g. /usr/libexec).

**Comment by leigh123linux** [comment]
@vladimir-didenko Can you post a link to the patch please.
