### ISSUE TITLE
[Feature Request]  fullscreen media player as lockscreen

### ISSUE THREAD

**Issue by hackoon** [linuxmint/cinnamon-screensaver#157]
It would be nice to have the gnome-mpv or vlc window as lockscreen combined with audio panel when activated only while playing fullscreen. 
- very usefull when playing a film, locking the screen while others continue watching.

**Comment by leigh123linux** [comment]
-1 against the idea, IMO the lock screen should be kept light not saddled with loads of crap.

**Comment by hackoon** [comment]
it doesn't add much to the lock screen it just needs to stay transparent as long as the player is playing. And for the crap its not about another shitty feature but very security related. it is as much "crap" as the audio panel - its just extents the feature to video too.
It would of course be nice to include fullscreen slide shows / presentations.

**Comment by hackoon** [comment]
Just did a few lines providing the feature. It's very small and affects only stage.py and x11.py.
Works only one single monitor yet, please test or give me feedback on how to set opacity for different monitors. Would also be nice to add a option in cinnamon-settings.

Features:
- no wallpaper image 
- no widgets apart from active unlock screen
- 100% transparency 
- checks if player is focused and has fullscreen dimensions
- changes transparency to 0% if player closes and puts widgets back (still without wallpaper)
- changes position of unlock and clock widget
- works with a range of players / slideshows

[mplayer_fs.patch.txt](https://github.com/linuxmint/cinnamon-screensaver/files/602337/mplayer_fs.patch.txt)
