### ISSUE TITLE
Feature request: Ability to disable clock/cover art movements (3.2.2)

### ISSUE THREAD

**Issue by saveman71** [linuxmint/cinnamon-screensaver#158]
In my opinion, it would be useful to add an option to disable, or at least change the frequency of the clock's and cover art random position changes.

Some arguments:
* We are in [current year], and CRT monitors have come to an end, I don't think ghosting/marking is a very important issue nowadays.
* The previous versions did not have this behavior
* It can be annoying to have something moving on a screen every two seconds or so when for example you are working aside the idle computer.

Otherwise, congrats for the release! Feels good to be able to control music/volume from the lock screen, at last!

**Comment by mtwebster** [comment]
Frequency increased here: 2f0cf18721657c65539 (this was never intended to be just 5 seconds.. I think I changed it at one point for testing something, and neglected to restore it.

Setting to disable: 63af9b83748122c5b - The ui for this has yet to be added to cinnamon settings, however dconf-editor or a terminal work for now.

For what it's worth, no consideration was taken for burn-in issues, I simply thought it would be aesthetically pleasing.

**Comment by saveman71** [comment]
Thank you!

**Comment by silverspr** [comment]
hi, how do I set the disable 63af9b8 in dconf editor? I'm using cinnamon 3.2.2
thank you for this fix as well

**Comment by leigh123linux** [comment]
@silverspr  I haven't got all day so no dconf-editor instructions, it's time to get your hands dirty and use CLI

```
gsettings get org.cinnamon.desktop.screensaver  floating-widgets false
```
