### ISSUE TITLE
[Feature request] Screensaver clock position setting options (cinnamon 3.2)

### ISSUE THREAD

**Issue by silverspr** [linuxmint/cinnamon-screensaver#161]
Have the ability to configure screen saver clock position as either random floating or stationary/locked position.  With stationary/locked position: have the ability to select placement of clock on screen or default to earlier build style (i.e. cinnamon 3.0.7).

Rationale: random bouncy is distracting if more than one computer/monitor are side by side

thank you for considering

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/158
