### ISSUE TITLE
3.2: Lock screen not displayed

### ISSUE THREAD

**Issue by jethrogb** [linuxmint/cinnamon-screensaver#163]
Since upgrading to 3.2, I frequently run into the issue where the DE becomes unusable after the screensave/lockscreen is supposed to have been activated. Instead of showing the lock screen, it will just show a screen capture of the desktop as it was when the screensaver turned on.

Sometimes, desktop hotkeys (close window, run command, expo mode, switch workspaces) etc. continue to work (including rendering of expo mode etc.) and I can exit this mode by doing run command: `killall cinnamon-screensaver-main.py`. Otherwise I'll have to go into the text mode terminal and do the same.

This only started happenning after I upgraded to 3.2. This seems to only happen when my music player (audacious) is running.

Arch Linux 4.8.10-1-ARCH
cinnamon 3.2.1-4
cinnamon-screensaver 3.2.2-1
lightdm 1:1.18.3-1

**Comment by JosephMcc** [comment]
Cinnamon screensaver needs to be updated. See https://github.com/linuxmint/cinnamon-screensaver/issues/159
