### ISSUE TITLE
[Regression] XScreenSaver Compatibility is gone in 3.2

### ISSUE THREAD

**Issue by feren** [linuxmint/cinnamon-screensaver#166]
Since 3.2, you can no longer use XScreenSavers as your screensaver on the lock screen...

**Comment by feren** [comment]
@mtwebster 
![screenshot from 2016-12-05 17-04-42](https://cloud.githubusercontent.com/assets/11057934/20894347/ee30ac34-bb0c-11e6-865d-386445221b18.png)

Cinnamon 3.2.2 on Linux Mint 18.0 (With 18.1 Repositories)

**Comment by leigh123linux** [comment]
Are the cinnamon-screensaver-x-plugin and cinnamon-screensaver-webkit-plugin packages installed?

**Comment by feren** [comment]
They used to be before the upgrade, hang on

**Comment by feren** [comment]
Fixed, thanks

**Comment by mtwebster** [comment]
Sorry I fiddled with the packaging a bit so people who didn't want that stuff could avoid it entirely.
