### ISSUE TITLE
Screensaver crashes when media application is open

### ISSUE THREAD

**Issue by alemedeiros** [linuxmint/cinnamon-screensaver#170]
I'm having trouble using the screensaver when a media player is open, I usually use [gpmdp](https://www.googleplaymusicdesktopplayer.com/), but I also tried locking the screen while running audacious, a more commonly used player and still got the problem.

The screensaver just hangs not appearing (leaving the screen frozen with all the windows as they were when I pressed the lock shortcut, changing to tty and back renders the screen black with the cursor appearing). This seems to happen when there is a song on the player (playing or paused)

When this happens, the only solution I could find was to kill the screensaver from the tty.

Since I couldn't easily find any log file, I ran `DISPLAY=:0 cinnamon-screensaver` from the tty and didn't get any different message with or without the player running. looking-glass didn't have anything either.

Is there any log file or anything I can do to help you understand what's happening? I loved the media feature.

I'm running Arch Linux with the following package versions: 
 - `cinnamon 3.2.1-4`
 - `cinnamon-screensaver 3.2.2-1`

**Comment by alemedeiros** [comment]
I just found out that disabling the `Show media player controls` makes it work fine.

Again if there is any verbosity flag I can set for the screensaver, I would gladly run to get the logs.

**Comment by mtwebster** [comment]
We're at 3.2.9 now - I'm fairly certain what you're describing has been fixed.
