### ISSUE TITLE
Setting "always show the clock" set off doesn't work right

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-screensaver#174]
The pop up for this setting says "show the clock always when true an not just on the lockscreen" (or similary). But when you set this to false, the clock is never shown.

**Comment by mtwebster** [comment]
I forgot to update the setting description for this - the function was changed to be consistent with the behavior of the rest of the 'widgets' in the screensaver.

So, the behavior is intended, the description is wrong.

**Comment by Mintulix** [comment]
Ok, so I'll close this. Thank you.
