### ISSUE TITLE
Short flicker when new screensaver starts to dim

### ISSUE THREAD

**Issue by Mintulix** [linuxmint/cinnamon-screensaver#177]
Change the start time for the cinnamon-screensaver (version 3.2.9) to 1 minute and wait this time. When it begins to dim, there is a single intensive flicker. The rest of the slow dimming time it's nice and ok.
This issue is only visible when you wait until the screensaver dims "for itself", not when you press "ctrl + alt + L" oder choose "lock screen" in the menu (then the dimming time is also shorter, very nice feature!).

**Comment by siduenho** [comment]
#202 is duplicate.

I'm sorry for that, but now we know that 3.2.13 is affected by this, too.

**Comment by Brightgalrs** [comment]
I'm have the same problem.

Nvidia drivers (nvidia-367) if that narrows things down.

**Comment by siduenho** [comment]
I'm using an Intel i5 6200U with The HD 520 graphics unit.

**Comment by margamanterola** [comment]
It seems https://github.com/linuxmint/cinnamon-screensaver/commit/2e73a9b44eb82b384bd698253a9e930bbb77aa50 addresses this issue.  I haven't been able to try it out yet.

**Comment by JosephMcc** [comment]
Yeah, I don't see the issue anymore.

**Comment by marga-debian** [comment]
Yes, this issue was fixed by the above mentioned commit.  I've verified that applying that fix makes the issue go away and the next upload to Debian will include that fix.
