### ISSUE TITLE
User info moves around the screen, periodically, with seemingly no option to disable

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/cinnamon-screensaver#179]
On Mint 18.0, I think that the text in question stayed put. I liked it that way. Seemingly now I cannot have it that way!

(Also, finding out which of the settings in the screensave options windows have helpful tooltips, and which do not is a bit tedious. One has to hover over all of them in turn.)

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/158
