### ISSUE TITLE
100% CPU Usage when using login screen from lock screen.

### ISSUE THREAD

**Issue by Weafyr** [linuxmint/cinnamon-screensaver#180]
Hello, I just upgrade my Mint from 18 to 18.1 and I think I found a bug in the screen saver. When I do the lock (ctrl+alt+l) the cinnamon screen saver will appear, there when I select that I want to use different user account and then I log in to the one I am actually using, after few seconds process `/usr/share/cinnamon-screensaver/pamhelper/cinnamon-screensaver-pam-helper` start to take 100% of 1 core of CPU. When I repeat this several times, I got new 100% consuming process for every try.
The version of cinnamon-screensaver is 3.2.9.
![snimek obrazovky porizeny 2016-12-19 05-59-26](https://cloud.githubusercontent.com/assets/24644737/21302435/0b42e274-c5b7-11e6-9797-9a282e968927.png)

**Comment by mtwebster** [comment]
I'll patch this later, I have a fix.  For what it's worth, the helper *only* exists when the unlock dialog is up (not when the screensaver is just idling with the background or whatever)

**Comment by Mintulix** [comment]
Sorry mtwebster, I think you misunderstood - the helper _should_ only exist when the unlock dialog is up, but that's not the case. The pam-helper process remains in a normal session with one core at 100% after fiddling around with two user logins.
See also https://github.com/linuxmint/cinnamon-screensaver/issues/182. For me it was an upgrade from Sarah, no fresh install.

**Comment by Alex74743** [comment]
I have the same issue with the process 'cinnamon-screensaver-pam-helper' using 25% of total CPU (100% of Core 3). This process is running at 25% total when logged back in.
I also upgraded to 18.1.
![screenshot from 2016-12-19 20-26-50](https://cloud.githubusercontent.com/assets/24659620/21328139/70058edc-c62a-11e6-9d44-fe1b78a43690.png)
![screenshot from 2016-12-19 20-26-32](https://cloud.githubusercontent.com/assets/24659620/21328140/70075ece-c62a-11e6-9794-25914eed8eff.png)

**Comment by Timmy93** [comment]
Like @Alex74743 I've one core at 100%.
I've made a clean install, no distro upgrade.
