### ISSUE TITLE
Unable to unlock cinnamon screensaver

### ISSUE THREAD

**Issue by asikroy** [linuxmint/cinnamon-screensaver#183]
This is my first attempt in reporting here in github so please bear with me if i have given inadequate info

I am a linux mint 18.1 user upgraded from 18, cinnamon edition, running cinnamon-screensaver 3.2.9

Just updated cinnamon edition 32 bit succesfuly only one issue with cinnamon screensaver whenever screensaver is activated and i enter my password unable to unlock screen pressing enter or the unlock icon using my cursor both are not working and only way to unlock my screen is by clicking on users icon in the screensaver going to MDM and entering password again there and entering it..although at the moment i have disabled screensaver and no problem at all any suggestion for fixing it is welcome.

Clem suggested Hi Roy, create a github issue for this if you can https://github.com/linuxmint/cinnamon-screensaver/issues. Kill the screensaver daemon and run it from the terminal to see if you can catch any error messages (killall cinnamon-screensaver; cinnamon-screensaver), lock the screen again, go to MDM, unlock, and see if there are errors in the terminal.

I have done killall cinnamon-screensaver and restarting it via terminal by running cinnamon-screensaver the result is
 ~ $ killall cinnamon-screensaver
 ~ $ cinnamon-screensaver
       Cinnamon Screensaver support not found in current theme - adding some...
       Trying to connect to logind...
       Starting screensaver...
       Successfully using logind
       Found no MDM server, ordering a new one
       Locking cinnamon-screensaver

This time too i have to unlock screensaver only via entering mdm

Iam using mint-y dark theme for desktop,windowborder,controls and mint-y icon set.

Iam using Zukwito circle theme for MDM

I dont know these two info has any relevance.. Thanks in advance.. happy christmas and aprosperous new year..

**Comment by wacher74** [comment]
See https://github.com/linuxmint/cinnamon-screensaver/issues/186

**Comment by imjeet** [comment]
Problem solved. Actually update manager showed some updates. After update the problem solved.
