### ISSUE TITLE
18.1 screensaver high cpu

### ISSUE THREAD

**Issue by agrisvv** [linuxmint/cinnamon-screensaver#184]
18.1 cinnamon screensaver hi cpu usage in attachment.
*in system monitor just end this processes and all work fine.
* end this processes, then work without problems.
* this bug may appear at system startup or after login after long time. i will write if i catch when problem come up. 

maybe help.
1. had two users.
2. 5 times day use user switching without logoff.
3. 2-3 days hibernate.
4. radeon hd video.
4. with mint 18.0 more times in week crash cinnamon helped force restart or ctrl alt+f2 to login again.

![screensaver](https://cloud.githubusercontent.com/assets/8926651/21403360/23e956fe-c7c5-11e6-98e2-
a59bb3382c14.png)

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/35dcf4e495b2ab940062cc5584b9c39a1495a189 and https://github.com/linuxmint/cinnamon-screensaver/commit/50e3b9c73faa7b5590cc3d4d7d27743ba64aed1e
