### ISSUE TITLE
No locking in suspend mode

### ISSUE THREAD

**Issue by artem-sidorenko** [linuxmint/cinnamon-screensaver#191]
After updating to Mint 18.2 I see this issue: when going to suspend-to-ram or suspend-to-disk I'm not forced to unlock the screen after resume.

Following screensaver configuration is used:

![screenshot from 2016-12-23 17-11-15](https://cloud.githubusercontent.com/assets/1645670/21457896/da9e86b2-c932-11e6-8060-b4d8b553dcf8.png)

Following screensaver version is used: 3.2.12+serena

**Comment by artem-sidorenko** [comment]
Hm. After the second reboot - the issue is gone. Any ideas how to collect the needed information when/if it happens again?

**Comment by mtwebster** [comment]
There have been a lot of updates to the screensaver, has this happened any more since?

Number of reboots wouldn't have mattered.. perhaps you updated also in the interim?

**Comment by artem-sidorenko** [comment]
@mtwebster Nope, I did not update.

Anyway, I did not see this issue anymore, maybe it was fixed by some of the updates
