### ISSUE TITLE
Any way to make the clock not move around?

### ISSUE THREAD

**Issue by mondalaci** [linuxmint/cinnamon-screensaver#198]
It'd be great if I could make the clock of the standard Cinnamon lock screen not move around. I think it'd result in a cleaner user experience. Any way to make it happen?

**Comment by leigh123linux** [comment]
Try

```
gsettings set org.cinnamon.desktop.screensaver floating-widgets false
```

**Comment by mondalaci** [comment]
Thank you, that seems to have worked!

It might be a good idea to expose this feature because right now it's burried deep within gsettings.

**Comment by leigh123linux** [comment]
Fixed by https://github.com/linuxmint/Cinnamon/commit/a625a9537806cab3c26a878a34c9e4aaa7ce3dbd
