### ISSUE TITLE
Feature Request: Leave a message

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/cinnamon-screensaver#20]
Going way back to the good old gnome 2 days, anyone could leave a message on your locked system that would pop up when you return to your desktop. I think it would be a good addition to the cinnamon-screensaver

**Comment by feren** [comment]
Can this issue be closed now there is such a feature?

**Comment by JosephMcc** [comment]
Read the previous posts more carefully. This isn't possible right now. Another person cannot come along a leave you a message on the lock screen unless I missed something.

**Comment by feren** [comment]
Oh ok, oops, there again, how would that be done without causing holes?

**Comment by ItzSwirlz** [comment]
I think this has already been implemented

**Comment by JosephMcc** [comment]
No it hasn't. It's the same as it's always been. I don't know that there are any plans for this.

**Comment by ItzSwirlz** [comment]
There's an away message. If I remember for UCR Hirsute testing I played with this. (Cs_screensaver.py)![image](https://user-images.githubusercontent.com/24401303/109508110-7baea880-7a6d-11eb-9f2e-4939bfeefa41.jpeg)

Does it count as a similar thing?

**Comment by JosephMcc** [comment]
No. The OP is talking about someone being to leave a message on the screen for you after it's locked. That is just the message you can set it to show before you lock it.

**Comment by JosephMcc** [comment]
I'm going to go ahead and close this. We don't keep all feature requests open but always keep the ideas in mind. Like I said before there are no plans for this as far as I know and it's been open a very long time.
