### ISSUE TITLE
crash of cinnamon-screensaver-main.py after unlock v3.2.13.1

### ISSUE THREAD

**Issue by nikaiw** [linuxmint/cinnamon-screensaver#200]
I hope this is not a known issue, the following crash sometimes happens to me using cinnamon-screensaver 3.2.13.1:

Traceback (most recent call last):
  File "/usr/share/cinnamon-screensaver/manager.py", line 325, in on_session_idle_changed
    self.despawn_stage(c.STAGE_IDLE_CANCEL_SPAWN_TRANSITION, self.on_despawn_stage_complete)
  File "/usr/share/cinnamon-screensaver/manager.py", line 177, in despawn_stage
    self.stage.cancel_unlocking()
  File "/usr/share/cinnamon-screensaver/stage.py", line 502, in cancel_unlocking
    self.unlock_dialog.cancel_auth_client()
AttributeError: 'NoneType' object has no attribute 'cancel_auth_client'

**Comment by mtwebster** [comment]
What distro is this on?

**Comment by nikaiw** [comment]
It's on ubuntu 16.04 - Xenial

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/6865bee0859e85939f94bbd64af0d208aedcaca2, though I haven't been able to reproduce this, or come up with a situation it would even happen, for that matter.
