### ISSUE TITLE
[ Feature Request ] Override wallpaper

### ISSUE THREAD

**Issue by imarkskinner** [linuxmint/cinnamon-screensaver#203]
So it would be cool if you could choose a different wallpaper for your lock screen, rather than defaulting to your desktop wallpaper and not giving you a choice about it.

It 'could' also give a workaround for the bug where the lock screen wallpaper doesn't respect the 'spanned' option and defaults back to 'scaled' as noted here on my other post https://github.com/linuxmint/cinnamon-screensaver/issues/127 people having problems could just choose a wallpaper that 'scales' well and at least have a normal looking wallpaper on their lock screen.

**Comment by mtwebster** [comment]
Spanned is now respected: https://github.com/linuxmint/cinnamon-screensaver/commit/0e589279eb07b52ecfc9b1ab456c7f07e973ecf5

**Comment by imarkskinner** [comment]
I no longer run unstable on my pc, I'll have to wait till this hits the stable release I expect in 18.2 and close issue #127 then unless anyone is happy that it's fixed and wants to close it.

**Comment by JosephMcc** [comment]
Thanks for the request but I don't think we are currently keen on supporting setting a different wallpaper for the lock screen.

**Comment by bastimeyer** [comment]
Being able to set a different wallpaper isn't just a matter of customizability, but also a matter of privacy to a certain degree. Not supporting a custom wallpaper forces users to change their desktop wallpaper before locking the screen (automatically or manually), which is quite a nuisance.
I'd kindly ask you to reconsider adding such a feature. Thank you!
