### ISSUE TITLE
[Critical] Screensaver and lock screen ignore scaling

### ISSUE THREAD

**Issue by Redsandro** [linuxmint/cinnamon-screensaver#204]
The screensaver, and more importantly, the lockscreen, don't cover the area of a monitor that was **scaled up** (zoomed out).

E.g.: `DVI-I-0: 1280x1024 +0+0 {viewportin=1965x1572}`

Afaik, scaling is not video driver specific and supported by all video drivers.

:warning: The part not covered by the lock screen still allows for mouse interaction, which is a security vulnerability.

![image](https://cloud.githubusercontent.com/assets/1702193/22147712/3fdad728-df0a-11e6-904c-eedc6896ed2a.png)

![image](https://cloud.githubusercontent.com/assets/1702193/16149377/a2fbd8cc-3490-11e6-9e5f-03ce46df2af2.jpg)

Here is an older bug report in the global cinnamon section: https://github.com/linuxmint/Cinnamon/issues/5385

**Comment by mtwebster** [comment]
Should be fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/c3715694aba68423bcde67b96b10462b41469939

Thanks

**Comment by Redsandro** [comment]
Thank you! Looking forward to trying this out.

Any idea or guess as to when this will go downstream into Mint? 18.1 or 18.2?

**Comment by Redsandro** [comment]
@mtwebster still seeing this issue on edge cases.

![image](https://user-images.githubusercontent.com/1702193/46566348-d08d7980-c91c-11e8-8699-6021fe0aff4c.png)

Should issue be reopened?

**Comment by mtwebster** [comment]
I'm trying to get these latest couple of commits out in a point release.  Although I haven't tested in this specific configuration, I'm reasonably confident the fixes I made will cover it (no pun intended) as well.

This commit:  https://github.com/linuxmint/cinnamon-screensaver/commit/02e6473393a8a497d0642ee3d7dfb73a7f3c14ae, is also related - it actually fixes the coverage issue.  The commit c0a3dd4 addresses the latency between configuration changes and screensaver response.

**Comment by Redsandro** [comment]
Nice, can't wait to test this out on my weird monitor setup.

**Comment by mtwebster** [comment]
cinnamon-screensaver was updated today to 3.8.3, which includes these fixes.

**Comment by Redsandro** [comment]
@mtwebster there appears to a possible regression or similar issues with the new Mint 21 i.e. cinnamon-screensaver 5.4.x+vanessa. There was an issue with the lock screen overlay being 1x scaling and the actual desktop being 2x scaling (4 times as big), which I believe was fixed in 5.4.2 since I cannot reproduce it anymore. There are however different users mentioning similar issues when using differently sized monitors [on the forum](https://forums.linuxmint.com/viewtopic.php?p=2218620#p2218620).

**Comment by Redsandro** [comment]
@mtwebster it occurred again using `cinnamon-screensaver 5.4.4+vanessa` (https://github.com/linuxmint/cinnamon-screensaver/commit/24eb3f7931e5bd73912b255c087f9fef7e44aca0). This is with High DPI and 200% scaling from the display dialog, single monitor.

![image](https://user-images.githubusercontent.com/1702193/190171809-378ae2db-1b81-49e5-8359-ef872ba28daf.png)

Top left is the lock screen. You can see Brave browser in the background. In this case it's a new tab.

For me, it happens very occasionally. I can't seem to force it. Sometimes I walk away and I get back and it's like this.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa

$ uname -a
Linux black 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Possibly related: 

- #409 
- linuxmint/cinnamon#5385
- linuxmint/cinnamon#10942

**Comment by lunalucadou** [comment]
I have noticed this as well from time to time. However, both my monitors are 1920x1080 96dpi (identical monitors both running at 1x scaling). It's very inconsistent, and the only common thread seems to be that it's only happened when the monitors wake up (I have my computer set to never suspend; instead, it turns the screens off after 30 minutes of inactivity).

My GPU is an AMD RX 6700 XT and I use the standard `amdgpu` drivers. The left monitor is connected via HDMI, the right monitor via a DP->DVI cable.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	Linux Mint 21
Release:	21
Codename:	vanessa
$ uname -a
Linux plumeria 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ apt show cinnamon-screensaver
Package: cinnamon-screensaver
Version: 5.4.4+vanessa
```

![PXL_20221123_172313981](https://user-images.githubusercontent.com/22415965/204146244-e74c2361-28fe-48fa-b726-277903d8d183.jpg)
