### ISSUE TITLE
Ability to suspend from lock screen with power button

### ISSUE THREAD

**Issue by jcogilvie** [linuxmint/cinnamon-screensaver#211]
See here:  https://github.com/linuxmint/Cinnamon/issues/5919 (note I am not OP but I concur with the request which was just closed with a suggestion to put it here)

I would like to be able to press the power button when on the lock screen and have it behave the same way it would during a logged-in session.  In my case I'd like the option to suspend.

**Comment by JosephMcc** [comment]
I agree with @leigh123linux in the original issue. I wouldn't want this behavior. I use the lock screen so people don't screw with my machine.

**Comment by jcogilvie** [comment]
I appreciate that perspective, so here's my response:  

Physical access is root access.  If someone wanted to screw with you they could just hold down the power button until the system is hard-shutdown, which is more risky to you.  Or press some alt+sysreq commands.  Or unplug it and eject the battery.  

Given this, the lock screen isn't a barrier to people screwing with your system, and I'd argue that was never the intent.  It's protection against someone pretending to be you and changing your system or others that it has access to.

I use the lock screen because work (wisely) mandates we lock our laptops when not at our desks.  But when I come back from an end-of-day meeting and want to pack it up and go home, it's superfluous to make me log in again before I can suspend and remove it from the docking station.

All that said, it doesn't really matter what my opinion is on what the lock screen is for; if the behavior is configurable, we can have options that will satisfy everyone.

**Comment by JosephMcc** [comment]
Can't really argue with that :)

**Comment by jjssoftware** [comment]
whilst I do agree with the sentiment of this idea, since you appear to be a laptop user I'm guessing that you already know that closing the lid when the lock screen is active can suspend the machine..so potentially no need to log in again before you suspend / remove from dock..

**Comment by jcogilvie** [comment]
My laptop sits closed on the dock.

**Comment by jjssoftware** [comment]
For me, a docked laptop with a closed lid == a laptop that is suspended to ram when the lid was closed.

**Comment by ava-dylang** [comment]
I think forbidding power-management at the login screen *by default* is a reasonable, _as a default_. :+1:

However I also have the ongoing desire for the option to enable power management without login.  

> it's superfluous to make me log in again before I can suspend and remove it from the docking station.
I agree strongly with this.

This request, for me, comes down to the necessity to _move_ a laptop, both in the sense of suspending (to deal with hardware workarounds), as well as in the sense of powering off the machine before traveling without an available power supply; That, and how both these cases are orthogonal to the device lock state.

An example of what I mean by that: Having locked the device, I often need to: suspend one machine before undocking and especially docking - for system stability, or Shutdown the hardware (gracefully) before travel with it unpowered (occasionally, daily, or frequently) and right now that requires me to take the time to login, to initiate the shutdown or suspend.

I hope that helps clarify why this, as an opt-in option would be valuable particularly to laptop users; even more particularly to laptop users who do not use lid-closed event to imply a poweroff or suspend event.

**Comment by erenoglu** [comment]
I'm the OP of the original bug report #5919, and I agree on the use case that @jcogilvie mentioned. I have the same issue, and I do not always have a keyboard with lid function (I use a fixed usb keyboard at work on my Surface Pro 3). 
When I'm back from a meeting and want to pack and go home, if I'm in Windows, I just unplug all usb / displayport stuff and then press power button, put it in my bag and go. Not possible when I'm using Cinnamon.

**Comment by dy10** [comment]
+1 for this request. I am currently looking for an alternative distro, just because of this issue.

**Comment by erenoglu** [comment]
I suggest trying Gnome on Mint. Normally GDM with Gnome has this ability. That's what i'm using now.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/bc966feacec2a53104b4e53a8b32cb6ec58866fd
