### ISSUE TITLE
Lock screen appears whilst the screen is dimming

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#217]
As I understand it, the screen is meant to dim, gradually, before the lock screen appears. I've seen a dimmed screen - my normal desktop, but dimmed - with the lock screen superimposed on it.

Mint 18.1 x64.
[EDITED to fix a missing letter and to replace an incorrect word.]

**Comment by marga-debian** [comment]
For how long?  If it's just a flash, then this was fixed with "stage/fader: Realize the stage offscreen, then reposition it before starting our fade in" (2e73a9b) + "stage.py: fix screen changed callback" (39da3f0).

If it's longer than just a flash then it might be something else, it would be nice if you could capture a video with your phone.

**Comment by ACinnamonUserInUK** [comment]
I think it was indeed just a flash. Moreover, I have not seen it for a while. (I have Cinnamon 3.2.)

**Comment by mtwebster** [comment]
It was never 100% reproduce-able - it seemed to happen randomly for me.. more or less or not at all depending on what type of graphics hardware or drivers I think.  But to be clear about that fix, it was added after 3.2

**Comment by CottonEaster** [comment]
I have had this problem, though in my case it took a good few seconds for the lock screen to fully overlay - replace, block - my original screen. It happened after a resume from sleep.

I do hope all these screensaver problems get fixed soon!

Mint 18.2.
Cinnamon 3.4.4.

**Comment by mtwebster** [comment]
Not being already locked when coming back from sleep should be fixed by https://github.com/linuxmint/cinnamon-session/commit/c2d18069e62c331ba65551871d2d15cd27ebbc85 (cinnamon-session 3.4.1)

**Comment by CottonEaster** [comment]
Ah. Sounds good. _However_:

```
~ $ cinnamon-session --version
cinnamon-session 3.4.1
```
That is: I seem to have that version of that package already - and I had the problem an hour ago.

**Comment by mtwebster** [comment]
Can you tell me was the sleep/suspend triggered by you (such as from the menu) or as a consequence of your power settings?  Also, was it suspend or hibernate?  And I assume you have "Lock the computer when put to sleep," but what is "Lock the computer after the screensaver starts" set to? (screensaver settings)

Thanks

**Comment by CottonEaster** [comment]
I think the power-saving state was _triggered by the power settings_, but I am afraid I do not quite remember.

The power-made entered was _suspend_, not hibernation.

The computer's BIOS asked for a password.

'Lock the computer when put to sleep' is set to: _yes_.

'Lock the computer after the screen saver starts' is set to: _yes_.

The computer did indeed lock, but, before it did that - or before I _verified_ that it had locked (I didn't touch the computer during the process I am about to describe) - the screen showed a slowly dimming desktop underneath the slowly appearing lockscreen.

_Mostly_, the locking works as it should - but not on this occasion (and not on at least one occasion with earlier versions of the screensaver).

**Comment by CottonEaster** [comment]
Perhaps I should add that the following appear in my logs.

```
dbus-daemon    A screensaver is already running!  Exiting...

dbus-daemon    Cinnamon Screensaver support not found in current theme - adding some...
```

**Comment by mtwebster** [comment]
This possibly fixes that issue: https://github.com/linuxmint/cinnamon-screensaver/commit/0ef2e27c6616bd5eceae27b0acdaa844403923b6

Though without a bit more to go on for reproducing, I can't be 100% certain.

**Comment by CottonEaster** [comment]
Thanks. I will await an update containing that patch.

**Comment by CottonEaster** [comment]
The computer exhibited the same behaviour again just now. Again, it was resuming from suspend, and I confident that this time the suspend was caused by inactivity rather than user command.

And I have various 'dbus' errors in the log ('Failed to construct signal', 'wpa_dbus_get_object_properties: failed to get object properties: (none) none') and also 'pkexec   pam_ck_connector(polkit-1:session): cannot determine display-device'.

**Comment by JosephMcc** [comment]
The dimming effect is gone so I don't know if this is even relevant anymore.
