### ISSUE TITLE
Cannot disable the fade effect in cinnamon-screensaver

### ISSUE THREAD

**Issue by phoenix-frozen** [linuxmint/cinnamon-screensaver#218]
cinnamon-screensaver is the only thing that doesn't have a setting to disable its animations. On older hardware, this would be really welcome.

I believe the necessary change is minimal: a dconf settings check near

https://github.com/linuxmint/cinnamon-screensaver/blob/db32ddf0a01f0abb8300563b30a1dee174aa8f99/src/manager.py#L94

so that it looks something like "if not self.stage or animations_disabled:", as well as a corresponding change at L108 of the same file.

**Comment by clefebvre** [comment]
We're getting rid of the fade-in effect.. it creates issues with suspend (takes too long.. 10 seconds) leading to cases where the screen isn't locked yet but we already suspended.. meaning the lock happens on resume instead.

And it creates critical issues with nouveau when the screen goes off.. on some hardware this impacts GTK, makes CSR to fail to lock, and causes freezes in Muffin.

so well, we're not keeping it.
