### ISSUE TITLE
Screensaver allows taking screenshots

### ISSUE THREAD

**Issue by s3lph** [linuxmint/cinnamon-screensaver#220]
Currently, cinnamon-screensaver does not prevent taking screenshots using the print screen key, which then end up in the user's pictures directory.

### Steps to reproduce
1. Lock your screen
2. Press the print screen key (May require Fn key on some keyboards)
3. Unlock the screen
4. Find the screenshot in your Pictures directory

### Expected behavior
Taking screenshots should not be possible while the screen is locked. Of course, this is discussable, but
I personally am not very fond of it.

### Actual behavior
A screenshot of the lockscreen is taken and saved on disk

### Environment
- OS: Arch Linux
- Cinnamon Version 3.2.8
- Cinnamon Screensaver Version 3.2.13

**Comment by jkirk** [comment]
Hey,

i am currently running LMDE 2 (with Cinnamon 3.4.4+betsy and Cinnamon Screensaver 3.4.1+betsy) and can *not* confirm this behavior. The print screen button has no effect when the screensaver is active.

**Comment by hitscanpro** [comment]
confirmed in cinnamon 3.4.4 and cinnamon-screensaver 3.4.1 arch64...
also confirmed on lmde2 same setup as @jkirk tho...
tested on both 32 and 64 bit lmde2 with cinnamon + betsy too...

**Comment by nick-s-b** [comment]
I've discovered this issue as well. I filed it against cinnamon repo but was directed to post it here:

https://github.com/linuxmint/Cinnamon/issues/6847

This could be a potential security/reliability issue depending on how you've partitioned your disk since the disk can be completely filled.

````
* Cinnamon 3.4.4
* Arch
* Nvidia binary 384.59 
* 64 bit
````

**Comment by leigh123linux** [comment]
@nick-s-b You do realize that most file systems reserve 5% of the space for root use only.

> depending on how you've partitioned your disk since the disk can be completely filled.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/bc966feacec2a53104b4e53a8b32cb6ec58866fd
