### ISSUE TITLE
glslideshow not killed on unlock: new copy created for each lock

### ISSUE THREAD

**Issue by sirg** [linuxmint/cinnamon-screensaver#222]
I use _glslideshow_ as my screensaver. With cinnamon-screensaver _3.2.13+serena_, every time the screen is locked, a new copy is started; the old copy is never killed. After a dozen locks/unlocks (common for day's work), CPU is 100% because there are a dozen instances of glslideshow running. This does not happen after resume from sleep, only on unlock when the box did not suspend/hibernate.

Workaround: put something like this in the background:
```
dbus-monitor --session type=signal,interface=org.cinnamon.ScreenSaver,member=ActiveChanged | \
while read _ val; do if [ "X$val" = "Xfalse" ]; then killall glslideshow; fi; done
```

**Comment by JosephMcc** [comment]
Xscrensaver support is gone and no longer supported.
