### ISSUE TITLE
Possible hang caused by a gksudo prompt when the lockscreen is active; how to tell programmatically when the lockscreen is running?

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#224]
I've a bash script that runs on a timer and, if it finds certain conditions to hold, asks the user, via an `gksudo` prompt, whether he wants to restart the network manager. I think that this might be hanging the computer: for, when the lockscreen is running, and `gksudo` grabs the mouse . . 

Now, I know `gksudo` has an option not to grab the mouse, but, at least on my system, using that option means the `gksudo` window is not drawn properly (for, rather, a rectangular subsection of the window gets made transparent); and, at any rate, isn't there a way of detecting, within Bash, when the lockscreen is active? Thanks.

**Comment by mtwebster** [comment]
You can use `cinnamon-screensaver-command -q` or `-t`, or directly use dbus - org.cinnamon.Screensaver is what cinnamon-screensaver-command hooks up to to control things.  You can parse the output of the command line, or the output of dbus-send.

**Comment by ACinnamonUserInUK** [comment]
Thank you.

**Comment by CottonEaster** [comment]
Sorry, but how does one use the DBUS method? I'd like to use that method because I need to run the query frequently and `cinnamon-screensaver-command -q` has proved expensive (because, I imagine, it has to load Python). I tried the following (having managed to find some documentation) but it does not work.

```
#!/bin/bash

screenSaverStatus=$(\
	dbus-send \
		--session \
		--dest=org.cinnamon.ScreenSaver \
		--type=method_call \
		--print-reply \
		--reply-timeout=20000 \
		/org/cinnamon/ScreenSaver \
		org.cinnamon.ScreenSaver.GetActive \
		boolean:true \
)
echo $screenSaverStatus
```
I get this error:

`Error org.freedesktop.DBus.Error.UnknownMethod: Method GetSessionIdleTime is not implemented on interface org.cinnamon.ScreenSave`r

**Comment by mtwebster** [comment]
Hmm that error doesn't even match the command - this works:

```
#!/bin/bash

screenSaverStatus=$(\
	dbus-send \
		--session \
		--dest=org.cinnamon.ScreenSaver \
		--type=method_call \
		--print-reply=literal \
		/org/cinnamon/ScreenSaver \
		org.cinnamon.ScreenSaver.GetActive
)
echo $screenSaverStatus
```
returns

```
   boolean false
```

**Comment by CottonEaster** [comment]
Thank you very much - and I am sorry for giving the wrong error message. (I pasted the wrong text for that.)

I note that on my system the `dbus` command is some ten times faster than the `cinnamon-screensaver-command`.

**Comment by mtwebster** [comment]
Just curious what you're trying to do - is there an issue in Cinnamon perhaps causing networking issues?  Or is it some quirk with your particular computer?  (I just don't want you to be forced to work around a bug, if there's something on our end)
