### ISSUE TITLE
Lock screen user icon image does not respect Cinnamon user icon sizes.

### ISSUE THREAD

**Issue by dgsan** [linuxmint/cinnamon-screensaver#226]
On default Mint 18.x install 2017-06-02.

By default user icons for Cinnamon are located in `/usr/share/cinnamon/faces`. They are all 96x96px.

The lock screen somehow uses `widgets/framedImage.py` in `unlock.py` to display these images at larger than 96x96px size and they look terrible when enlarged. Even odder, putting larger images in `/usr/share/cinnamon/faces` does not fix this pixelation issue. I don't really know pyGTK at all, so particularly in light of larger images not changing anything not really sure what to make of it (if larger images fixed I'd have assumed it was a theme issue).

Update: It seems to be a CSS issue. I think setting min height of the appropriate theme elements to 96px works as a fix (presumably this means that when user icons are loaded they get resized to the standard 96px internally? obviously not familiar with this project/gtk at all, ha ha).

**Comment by mtwebster** [comment]
Well, selecting a 150px image *should* work - I'll see why not.  I never noticed much degradation in the face pics when shown in the lockscreen, though I am most definitely not an expert on whether something looks good or not, when it comes down to this sort of thing.  I'll do a bit of testing, as well as see what changing the default size would look like on the lockscreen.

**Comment by mtwebster** [comment]
Should be addressed by https://github.com/linuxmint/cinnamon-screensaver/commit/f1157ffdd426a874dbf70ab3420147cba648a487
