### ISSUE TITLE
Cinnamon 3.4: Second display stuck

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon-screensaver#227]
Linux Mint 18.2 beta with Cinnamon 3.4.1 (64 bit):

Define in the screensaver settings the user format %H;%M:%S and start the screensaver.

Expected: You see the running seconds in the clock display.

Actually you get the seconds value for the time the screensaver gets started. The seconds display change after that only once per minute exactly at 00 seconds.

This bug does actually exist also in Cinnamon 3.2. Up to inclusive Cinnamon 3.0 the seconds display as expected and update secondly.

**Comment by mtwebster** [comment]
fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/9fb736e0310321e1fca40b2b2d52cb2549f4bba3
