### ISSUE TITLE
Screensaver in guest account

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon-screensaver#228]
Mint 18.2 beta Cinnamon 64 bit.

Once the screensaver starts in the guest session, it is impossible to get back to the desktop. Pressing simply the Enter-key for the password request gives the warning, that the password is wrong.

The only chance to get out is to go the login screen. If I try to start now a new guest account session it takes noticeably far more time, until I get into the guest account desktop (in comparison to the first guest account).

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/1f9c1a59a697cd4cc94ba60845cf891060885c66
