### ISSUE TITLE
Screensaver not blocking for new accounts without password

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/cinnamon-screensaver#229]
Mint 18.2 beta Cinnamon 64 bit.

If you create  a new user account, there will be by default no password be set. If the new user now wants to lock the screen, he cannot, as the desktop reappears as soon as the mouse or a key get touched. This with the very default screensaver settings. (If the admin has set up a password, all works as expected.)

No screen locking without password is obvious. But the problem is related with another problem (I do not see, on which place to report it, so I add the details here):

A new account (without admin-privileges), which (by default) has no password set, cannot create a password via account details. Even if the user defines a qualified new password and confirms it with a second entry, the OK button keeps grayed out - obviously because of the missing "old" password (which cannot be given, as it does not exist). This is obviously a limitation of the account detail dialog, not of the system itself, as the user can set a password easily on the command line.

As in Mint 18.2 a new account does no longer get added to the nopasswdlogin group (good change) it would be now an easy task, to create a new account and the new user could set up the password on its own. But this should be doable on the obvious graphical place (user applet -> account details) without the need to give the new user at first an advice, how to use the command line.

**Comment by clefebvre** [comment]
The second part is valid, but this should be against cinnamon itself, not cinnamon-screensaver.
