### ISSUE TITLE
python3-xapp 1.0.1 dependency error on Ubuntu

### ISSUE THREAD

**Issue by belandsoft** [linuxmint/cinnamon-screensaver#231]
I was trying to install cinnamon-screensaver from

https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly/+index?batch=75 

on Ubuntu 17.04 x64, but I can't instal it because of dependency error:

> python3-xapp (>= 1.0.1) required but version 1.0.0-2 is to be installed

**Comment by leigh123linux** [comment]
Not our problem.

**Comment by JosephMcc** [comment]
python3-xapp is not currently part of the nightly builds ppa. You need to build it yourself from https://github.com/linuxmint/python-xapp
