### ISSUE TITLE
Commands to check screensaver do not work as root - a bug?

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#235]
* Cinnamon-Screensaver version (cinnamon-screensaver --version)
 * Distribution - Mint 18.2
 * Graphics hardware *and* driver used: Intel on-board graphics; Mesa DRI Intel(R) 965GM 
 * 32 or 64 bit

**Issue**

```
Laptop lib # cinnamon-screensaver-command -q
Can't connect to screensaver!
```

```
#!/bin/bash
screenSaverStatus=$(\
dbus-send \
	--session \
	--dest=org.cinnamon.ScreenSaver \
	--type=method_call \
	--print-reply=literal \
	/org/cinnamon/ScreenSaver \
	org.cinnamon.ScreenSaver.GetActive
)
echo "$screenSaverStatus"
```

Produces: `Can't connect to screensaver!`

**Steps to reproduce**

Please see above.

**Expected behaviour**

I'd expected the commands to work.

**Other information**

The commands I've given work fine when I'm not root.

**Comment by jaszhix** [comment]
Cinnamon and its components don't run as root (because its dangerous), so I don't think this is a bug.
