### ISSUE TITLE
xscreensaverhack memory leak

### ISSUE THREAD

**Issue by hitscanpro** [linuxmint/cinnamon-screensaver#236]
```
3.4.1  * Cinnamon-Screensaver version (cinnamon-screensaver --version)
arch  * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
old laptop stuff nothing special * Graphics hardware *and* driver used
64  * 32 or 64 bit
 ```

the program called by org.cinnamon.desktop.screensaver xscreensaver-hack is put to sleep when the mouse is moved

few minutes pass its started again, move the mouse, now 2 instanxes of xmatrix?

repeat until 999 instances of xscreensavers or 0mb in ram whichever is first

should either kill the xscreensaver on exit or reuse the old one again

cheers guys cinnamon by far best linux desktop keep up the good work

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by icarter09** [comment]
@hitscanpro are you still experiencing this issue? If so, what version of cinnamon-screensaver are you using?

**Comment by JosephMcc** [comment]
Xscrensaver support is gone and no longer supported.
