### ISSUE TITLE
Cinnamon-screensaver bypassable in VMware Workstation

### ISSUE THREAD

**Issue by CatCookie** [linuxmint/cinnamon-screensaver#239]
```
 * Cinnamon 3.4.6
 * cinnamon-screensaver 3.4.2
 * Distribution - Mint 18.2
 * Vmware Workstation 12.5.7 build-5813279 Pro
 * 64 bit
 ```

**Issue**
When resizing a locked VM window and going into fullscreen after that, the lock-screen still has focus, but has the size of the smaller, resized window.
Then you can paste commands into an open terminal (with middle mouse button) or copy information out of an open terminal. 
Keyboard focus is still on the lockscreen.

**Steps to reproduce**
* Open Terminal window
* Resize VM window
* Put VM in fullscreen again
* Paste 'killall cinnamon-screensaver <linebreak>' into open terminal. (middle mouse button)
-> Lockscreen bypassed

**Comment by mtwebster** [comment]
Unfortunately I can only test this on virtualbox (mint on a mint host) currently, and it works fine there.

Are you on a windows or linux host?  I'll attempt to reconstruct this if possible, it's been a few years since I used vmware.

**Comment by CatCookie** [comment]
It is a Windows 10 Host and i can't reproduce it on virtualbox either.

**Comment by mtwebster** [comment]
@kykrueger for the latest release as you mention, is cinnamon-screensaver up-to-date?  (3.4.2)

You can run `cinnamon-screensaver --version`

**Comment by kykrueger** [comment]
Unfortunately yes.  My output was as follows. 

```
cinnamon-screensaver --version
cinnamon-screensaver 3.4.2
```

I reproduced the problem today, including the ability to kill the screensaver from an open terminal. 

Please let me know if there are any more useful details I can provide.

-- Kyle

**Comment by mtwebster** [comment]
Confirmed in vmware player 12 on a Windows 10 host

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/0abbeba38b2d04fc45c871e3b747e069292da2f0

I'll provide some packages for people on Mint to try if wanted, and I'll try to get a point release out

**Comment by mtwebster** [comment]
Please see [this](https://github.com/linuxmint/cinnamon-screensaver/issues/246#issuecomment-330129006) comment.
