### ISSUE TITLE
Lock screensaver is not enabled automatically

### ISSUE THREAD

**Issue by areynaldos** [linuxmint/cinnamon-screensaver#24]
Since I updated to LM 15, with Cinnamon 1.8.8, the screensaver never kicks in. No matter if I set it lock the screen after 30 seconds, the screensaver and lock do not work.

Only if I enable them manually through the menu or CTRL-ALT-L it works.

This was a couple of open bugs in the Cinnamon project (one of them was closed commenting to add a bug here) and one remains open as Cinnamon #1765.

Thanks,

**Comment by Vahan86** [comment]
@areynaldos, is this still an issue for you with Cinnamon 3?
