### ISSUE TITLE
Feature Request: Allow ability to disable fade

### ISSUE THREAD

**Issue by dcharles** [linuxmint/cinnamon-screensaver#241]
```
 * Cinnamon-Screensaver version: 3.2.13
 * Distribution: Debian 9.1
 * 32 or 64 bit: 64-bit
 ```
I find the fade-to-screensaver behavior of the Cinnamon screensaver very distracting. I would much prefer if my screen immediately cut to black. It would be nice if the fade could be enabled or disabled with a checkbox in the Screensaver settings window.

**Comment by JosephMcc** [comment]
The fade is no longer used.
