### ISSUE TITLE
Screensaver doesn't cover all screens after resuming from suspend

### ISSUE THREAD

**Issue by psygnoser** [linuxmint/cinnamon-screensaver#244]
```
 * Cinnamon-Screensaver version - 3.4.2
 * Distribution - Fedora 26
 * Graphics hardware *and* driver used - Nvidia with proprietary drivers 384.69
 * 64 bit
 ```

After resuming from suspend, having plugged in a different set of external monitors than before the suspend, the screensaver only appears on my laptop monitor but not on the other two external monitors which leaves the desktop fully exposed - it can be interacted with as if it were unlocked!?

The two monitors are plugged in via laptop's docking station via dvi and a display port.
This issue doesn't seem to occur in another setup where I have a different external monitor connected directly via vga port. 

Reverting back to 3.4.1 fixes the issue!

**Comment by mtwebster** [comment]
If DisplayPort is involved, I'm not surprised, sometimes you don't get plug events from them.  This includes conversions to/from DP in a cable.  I gave up and went back to using hdmi, dvi and vga, which all seem to be reliable as far as this goes.

There's nothing that can be done about this for now, at least by us.  3.4.2 should have fixed most of these issues, I expect if downgrading worked for you, it is largely due to luck.

**Comment by psygnoser** [comment]
Well I've been using the current hardware configuration/setup for more than a year now and there were never any issues regarding the screensaver until the very last update so I really don't understand how this is related to luck?

**Comment by Piiit** [comment]
I had the same issue here. 
![img_20170915_094452](https://user-images.githubusercontent.com/6096063/30473112-700fb30e-99ff-11e7-928f-1ad8a999dbc6.jpg)

I use a VGA cabel to attach the external monitor. I put the laptop into standby without any external connections to monitors. I resumed it afterwards, while I had the VGA cabel already attached before pressing "wake-up". 

LM 18.2 Intel i915 Graphics

**Comment by mtwebster** [comment]
@Piiit what version of cinnamon-screensaver?

**Comment by Piiit** [comment]
@mtwebster 
```
$ cinnamon-screensaver --version
cinnamon-screensaver 3.4.2
```

**Comment by mtwebster** [comment]
Please see [this](https://github.com/linuxmint/cinnamon-screensaver/issues/246#issuecomment-330129006) comment.

**Comment by mtwebster** [comment]
Any feedback from the previous comment (and the packages there to try)?
