### ISSUE TITLE
Blinking Screen

### ISSUE THREAD

**Issue by SimaKyr** [linuxmint/cinnamon-screensaver#247]
```
??
 Mint 18.1 Cianamon
 Inter Corporation Core Proccesor Integrated Graphics Controller
 64 bit
 ```

When Linux switches to lock mode, the whole screen flashes before the animation

**Comment by SimaKyr** [comment]
Hm...My issues...

**Comment by icarter09** [comment]
@SimaKyr is this still an issue or can this ticket be closed out?

**Comment by SimaKyr** [comment]
It issue can be fixed with update to latest version Linux Mint
