### ISSUE TITLE
Request for authentication *after* resuming from suspend

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#252]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 3.4.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.2
 * Graphics hardware *and* driver used:  Intel Corporation Mobile GM965/GL960; 2.1 Mesa 17.0.7
 * 32 or 64 bit: 64
 ```

**Issue**

Since the recent screensaver update, I get a dialog asking for authentication to 'suspend the system' immediately after unlocking after resuming from suspend.

**Steps to reproduce**

Wait for computer to suspend. Resume by pressing a key. Enter password on lockscreen. Encounter authentication dialogue (a second one, not on the lockscreen but on the desktop).

**Expected behaviour**

One authentication - on the lockscreen and not the desktop - is enough.

**Other information**

EDIT: I've got this in the log:
`
pam_ecryptfs: seteuid error`

**Comment by JosephMcc** [comment]
Can you show a screenshot of this second dialog on the desktop? I've never seen it.

**Comment by CottonEaster** [comment]
I'll try to get a screenshot the next time I have the problem. I have not had the problem for some months, I am pleased to report.

**Comment by JosephMcc** [comment]
Ok. I'm closing this for now then.
