### ISSUE TITLE
Lockscreen seems to indicate two notifications; returning to desktop reveals none

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#254]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 3.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * 32 or 64 bit: 64
 ```

**Issue**

The lckscreen seems to indicate two notifications - for, in its top right, it displayed what looks like a pause icon, together with the number 2. Perhaps the problem is that those indicators are not properly explained - do they mean there are two notifications waiting? At any rate, upon returning to the desktop, I hover over the notifications applet and it says there are no notifications.

**Steps to reproduce**

Unknown.

**Expected behaviour**

**Other information**

**Comment by mtwebster** [comment]
If you feel you could reproduce this, could you run `cinnamon-screensaver --debug` so we can try to identify the notification source?  We should already be filtering out certain items, but its expected behavior is slightly different from the notification applet.

**Comment by CottonEaster** [comment]
Thanks. Let me check I understand. If and when the problem recurrs, I should immediately run `cinnamon-screensaver --debug` and then report the output here - yes? I can do that. (But must I do something like `killall cinnamon-screensaver` first?)

**Comment by mtwebster** [comment]
Kill the existing process first and then run it in debug mode. Then just operate normally until (hopefully) the issue occurs. Then you should be able to see what the notification was in that terminal after unlocking.

**Comment by CottonEaster** [comment]
The problem recurred just now: five notifications shown on the lockscreen, none visible on desktop. So, hoping the problem would reoccur, I followed your instructions (mtwebster) - but perhaps without success?

```
~ $ killall cinnamon-screensaver
~ $ cinnamon-screensaver --debug
Debug mode active
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
A screensaver is already running!  Exiting...
```

**Comment by CottonEaster** [comment]
Also, I have this in the systemlog, at approximately the time of the problem:

`cinnamon-screensaver-pam helper pam_ecryptfs: seteuid error`

**Comment by CottonEaster** [comment]
I've got some useful data. After one disappearing notification was seen on the lock screen, the terminal produced the following.

```
Notification received...
Sender: thunderbird
Summary: [redacted] has new mail
Body: From [redacted]
[Title redacted]
Found 1 Xinerama screens on display :0
Monitor 0 is 0,0 1280 x 800
Cinnamon Screensaver compiled without Solaris Xinerama support
Scale factor of 1 applied.  Monitor 0 is 0,0 1280 x 800
Stage.update_geometry - new backdrop position: 0, 0  new size: 1280 x 800
Notification received...
Sender: thunderbird
Summary: [redacted] has new mail
Body: From [redacted]
[Email title redactged]
authClient initialize... initialized already: False
pam_start ("cinnamon-screensaver", "[my username - redacted]", ...) ==> 0 (Success)
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
authClient idle add auth-prompt
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
authClient idle add auth-busy
Output from pam helper: ''
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient initialize... initialized already: True
authClient message to child
authClient initialize... initialized already: True
auth_message_handler processing response string
should interrupt: 0
Got response
Got respose to message style 1: interrupt:0
Msg handler returned 1
Output from pam helper: 'CS_PAM_AUTH_BUSY_TRUE'
authClient idle add auth-busy
Output from pam helper: ''
   pam_authenticate (...) ==> 0 (Success)
pam_acct_mgmt (...) ==> 0 (Success)
   pam_setcred (...) ==> 0 (Success)
 pam_end (...) ==> 0 (Success)
Verify user returned: TRUE
Output from pam helper: 'CS_PAM_AUTH_SUCCESS'
authClient idle add success
Output from pam helper: ''
authClient message to child
authClient helper process completed...
CsScreen dispose
CsScreen finalize
```

I note that Thunderbird was indeed running during the time at issue and that my Thunderbird extensions include the following.

(1) Enhanced Desktop Notifications

> Provides enhanced desktop notifications using the notify-send library.Provides enhanced new mail desktop notifications using the notify-send library. Notifications differ from the built-in notifications in that they have a nicer icon, group many new mail notifications into one, and show notifications for the currently opened folder (useful if you keep Thunderbird minimized).

(2) Messaging Menu and Unity Launcher integration

> This extension integrates Thunderbird into the Ubuntu Unity messaging menu and launcher

**Comment by mtwebster** [comment]
Do you ordinarily get thunderbird notifications when you're at the computer?  do they stick around or disappear immediately?  Those seem like valid notifications, I'm just wondering why you're not seeing them sitting in the tray when you unlock your computer.  Do you have notifications turned off in settings?  Do you have them set to expire?

I'll play around with thunderbird, at least it's something relatively easy to reproduce.  Thanks

I don't think the pam-helper message is relevant (I think this happens because the screensaver runs in user mode, not root,) but I'll keep an eye out for it while testing.

**Comment by CottonEaster** [comment]
> Do you ordinarily get thunderbird notifications when you're at the computer?

Yes, both in the form of a number (= number of unread e-mails) appearing on the plank Thunderbird icon, and in the form of Mint's standard (`notify-send`) notifications.

> [D]o they stick around or disappear immediately?

The former - the plank numbers - persist. The latter - the notifications proper disappear from the screen after a short period - which owes to the expiry setting, yes? Yet, the the notifications are still to be found, I think, via the notifications applet. (In that applet's settings, I have 'ignore transient notifications' set to true, though I am unsure how that is meant to work.
