### ISSUE TITLE
Create man pages for cinnamon-screensaver and cinnamon-screensaver-command

### ISSUE THREAD

**Issue by schachmat** [linuxmint/cinnamon-screensaver#261]
We should have man pages for these two programs. Lintian fails with:

```
cinnamon-screensaver: binary-without-manpage usr/bin/cinnamon-screensaver
cinnamon-screensaver: binary-without-manpage usr/bin/cinnamon-screensaver-command
```

**Comment by leigh123linux** [comment]
Feel free to write them if you want them as I doubt any priority will be given to this minor issue.

**Comment by icarter09** [comment]
@leigh123linux should this ticket be closed? I don't believe this issue was ever worked on.

**Comment by icarter09** [comment]
@schachmat thanks for putting up the PR! I should have tagged you in the question to see if you had worked on it any. My bad.
