### ISSUE TITLE
Screen Locker compromises security

### ISSUE THREAD

**Issue by patricktokeeffe** [linuxmint/cinnamon-screensaver#262]
This has bothered me for a long time. (Maybe it's been fixed since 3.2.13)

**Issue**

The screen lock utility suspends the screensaver timer function, effectively disabling all screen security. If a user fails to manually initiate screen lock by pressing OK (i.e. they forgot or missed the Enter key or walked away before seeing the dialog), the computer will remain unlocked indefinitely. 

**Steps to reproduce**

Select <kbd>Menu</kbd>&rarr;<kbd>Lock Screen</kbd> but do not press <kbd>Cancel</kbd> or <kbd>OK</kbd>. 

**Expected behaviour**

The screensaver should engage after it's delay timer regardless of the state of Screen Locker.

**Other information**

Clicking "Lock Screen" runs this: 
```
sh -c /usr/share/cinnamon/cinnamon-screensaver-lock-dialog/cinnamon-screensaver-lock-dialog.py
```

**Observed on:**
```
System:    Host: tower Kernel: 4.4.0-104-generic x86_64 (64 bit gcc: 5.4.0)
           Desktop: Cinnamon 3.2.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.1 Serena
Machine:   System: Dell product: OptiPlex 760 Chassis: type: 6
           Mobo: Dell model: 0G214D v: A00 Bios: Dell v: A01 date: 12/03/2008
CPU:       Dual core Intel Core2 Duo E8400 (-MCP-) cache: 6144 KB
           flags: (lm nx sse sse2 sse3 sse4_1 ssse3 vmx) bmips: 11970
           clock speeds: max: 2992 MHz 1: 2992 MHz 2: 2992 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] RV620 LE [Radeon HD 3450]
           bus-ID: 01:00.0 chip-ID: 1002:95c5
           Display Server: X.Org 1.18.4 drivers: ati,radeon (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.00hz, 1280x1024@60.02hz
           GLX Renderer: AMD RV620 (DRM 2.43.0 / 4.4.0-104-generic, LLVM 5.0.0)
           GLX Version: 3.0 Mesa 17.2.4 Direct Rendering: Yes
 ```
*Note I'm still using Mint 18.1/Cinnamon 3.2.7*

**Comment by leigh123linux** [comment]
Feel free to reopen if you can reproduce with 3.6.x as 3.2.x is unsupported.

**Comment by patricktokeeffe** [comment]
Happy to say it's staying closed
