### ISSUE TITLE
excessive memory usage

### ISSUE THREAD

**Issue by deutrino** [linuxmint/cinnamon-screensaver#267]
* Cinnamon-Screensaver version: 3.6.1
 * Distribution: Mint 18.3
 * Graphics: Intel Haswell-ULT Integrated Graphics Controller (i915) on a Dell Latitude E5540 typically with a second external display
 * Linux 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Issue**

cinnamon-screensaver uses far more RAM than I believe it should, the value seems to grow slowly with uptime though I have not verified this. I've seen values from 280-330MB when the system is in use and no screensaver is running.

**Steps to reproduce**

Use cinnamon-screensaver as provided with Mint 18.3 with the xscreensaver 'galaxy' screensaver.

**Expected behaviour**

cinnamon-screensaver should not use hundreds of megs of RAM, particularly when no screensaver is running.

**Other information**

Please let me know if there are tests I can run to add more useful information.

**Comment by JosephMcc** [comment]
XScreensavers are no longer supported. If you still see an issue in 4.0 please add more info to the already open issue: https://github.com/linuxmint/cinnamon-screensaver/issues/72
