### ISSUE TITLE
Screensaver says 'no comment' (!)

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#268]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 3.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Intel Open Source Technology Center; Mesa DRI Intel(R) 965GM; 2.1 Mesa 17.2.8
 * 32 or 64 bit: 64-bit
 ```

**Issue**

Curiously, the lock screen today said, 'No comment', just above my user picture. I took a photo with my phone but the image did not come out (because of the flash).

**Steps to reproduce**

Unknown. I've never seen this before.

**Expected behaviour**

I think the area of the screen that is at issue is normally blank and no so sardonic.

**Other information**

It may be relevant that, after a hard reboot to escape a hang (a hang caused by network shennanigans), my normal user lost most of its group memberships, including sudo. I've restored all those memberships, I think, but it may be affecting the lock screen.

I will report back on whether the problem persists.

**Comment by JosephMcc** [comment]
If you cannot supply some means for us to reproduce or troubleshoot this issue then there isn't much that can be done.
