### ISSUE TITLE
Screen contents are visible briefly before the locker kicks in

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#269]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 3.6.1.
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
 * Graphics hardware *and* driver used: Mesa DRI Intel(R) Kabylake GT1.5; 3.0 Mesa 17.2.8
 * 32 or 64 bit: 64
 ```

**Issue**

The contents of the screen flash up - for about a second - before the screensaver kicks in.

**Steps to reproduce**

Set a lapto to do the following on lid-close: (1) suspend; (2) lock screen.
Close the lid
Wait a few seconds (I do not think the amount of time matters, so long, at least, as the computer does not suspend).
Open the lid. Observe the brief flashing up of the unlocked screen.

**Expected behaviour**

The unlocked screen should not be visible at all, until the computer has been unlocked.

**Other information**

I am using a fast computer (quad-core X1 Carbon with PCI-SSD).

**Comment by mtwebster** [comment]
Finally managed to reproduce this (there are a few other issues open about it) -

This should solve the problem:

https://github.com/linuxmint/cinnamon-settings-daemon/commit/7c3801820f7a3e71dc0c713d4fda9fa7725108e1

**Comment by CottonEaster** [comment]
Marvellous! So if i want this fix now I have to compile that file and put the result . . where? I can't find anything called `csd-power-manager' on my system. Or will the change be conveyed in an immanent update via Mint's Update Manager?

**Comment by mtwebster** [comment]
You can try installing packages from here: https://github.com/linuxmint/cinnamon-settings-daemon/releases/tag/master.mint18

They're auto-generated on a Mint 18 virtual build - I just tested it on my Mint 18.3 box, it seems fine.  

Mintupdate (or apt-get) will want to revert you to the current distro-version, if something goes wrong.

**Comment by CottonEaster** [comment]
Thanks. The download contained two files, though (aside from a changelog). I fiddled around and it seems that it is the smaller (< 10 K!) one that I should install (and do an `apt-hold` on), yes? Also: any idea when the fix will come out officially? In Mint 19? Before that? Thanks.

**Comment by mtwebster** [comment]
You should download and extract the package.tar.gz file, extract the packages folder, and install both .deb packages (from a terminal, `sudo dpkg -i cinnamon-settings-daemon*.deb`)

Definitely Mint 19, I mentioned a point release also prior to that, but don't know yet.

**Comment by CottonEaster** [comment]
Those new packages stopped my laptop's special keys - volume, brightness - from working. Well, it seems that either they did that, or my using `apt-mark hold` on the packages did. So I've restored the normal versions of the packages and all is well.

**Comment by CottonEaster** [comment]
I fear this needs re-opening, because it occurs occasionally on Mint 19 Cinnamon.

**Comment by mtwebster** [comment]
See https://github.com/linuxmint/Cinnamon/issues/4324

I'm fairly certain this isn't a screensaver issue at this point.
