### ISSUE TITLE
User installed webkit screensavers

### ISSUE THREAD

**Issue by smurphos** [linuxmint/cinnamon-screensaver#272]
```
 * Cinnamon-Screensaver version - 3.6.1+sylvia
 * Distribution - 18.3
 * Intel 2nd Generation Core Processor Family Integrated Graphics Controller
bus-ID: 00:02.0
Display Server: X.Org 1.18.4 drivers: (unloaded: fbdev,vesa)
Resolution: 1366x768@60.03hz
GLX Renderer: Mesa DRI Intel Sandybridge Mobile
GLX Version: 3.0 Mesa 17.2.8 Direct Rendering: Yes
 * 64 bit
 ```
I'm exploring the feasibility of a spice being able to add additional webkit screensavers. As it stands I've made some simple additional webkit screensavers in `/usr/share/cinnamon-screensaver/screensavers/webkit@cinnamon.org` which works fine.

I've also tried a creating  `~/.local/share/cinnamon-screensaver/screensavers/webkit@cinnamon.org` folder and moving some of those screensavers in there. 

Screensavers in this location do appear in the settings app as options, but fail to preview in the setting app with  `Error opening file: No such file or directory`

So is this partially implemented functionality, a bug, or something else? 

**Steps to reproduce**

Easiest way is probably to create the folder location and as above and then copy over the default webkit-stars screensaver and temporarily delete from the original location. It will still appear in the settings list but will fail to preview. If deleted from both locations it will be removed from the options in the settings app.

**Expected behaviour**

It would be nice if there was a way for end users and or a spice to install additional webkit screensavers without having to access sudo 

**Other information**

**Comment by mtwebster** [comment]
This was always supposed to be possible, I just don't think anyone ever checked that it worked :)

**Comment by smurphos** [comment]
Easyfix - I should have spotted that. Thanks ;-)
