### ISSUE TITLE
Bug on Login Scrren

### ISSUE THREAD

**Issue by ValneyFaria** [linuxmint/cinnamon-screensaver#273]
```
 * Cinnamon-Screensaver version (3.6.1)
 * Distribution - (Mint 18.3)
 * Intel Corporation 3rd gen Core Processor Graphics Controller
 * 64 bit
 ```

**Issue**

When you turn on your Computer, the Login screen resolution for password insertion looks like a 800x600 screen.

**Steps to reproduce**

I don't know.

**Expected behaviour**

The Resolution shoulb be the same of the computer.

**Other information**

**Comment by icarter09** [comment]
@ValneyFaria are you still having this problem? If so, what version of Mint and Cinnamon are you now using?

**Comment by ValneyFaria** [comment]
Hi Isaac. I’m using Linux Mint Sarah 19 right now and the problem is solved. Thank you so much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by icarter09** [comment]
@ValneyFaria glad to hear that and thanks for the quick reply! Can you close this ticket whenever you have a chance? Thanks!

**Comment by ValneyFaria** [comment]
Of course. Have a great night!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
