### ISSUE TITLE
3d-objects turned inside-out

### ISSUE THREAD

**Issue by ssv-170379** [linuxmint/cinnamon-screensaver#278]
```
cinnamon-screensaver 3.6.1
Mint 18.3 sylvia
GeForce GTX 1060 6GB, NVidia proprietary driver ver. 384.111
64 bit
 ```
Most of 3d-screensavers have objects turned inside-out (bad normals?) like this https://i.imgur.com/0d1tWn2.png

**Comment by JosephMcc** [comment]
This looks like an issue with the actual xscreensavers being used. Not with cinnamon-screensaver itself.

**Comment by ssv-170379** [comment]
Seems that not. https://i.imgur.com/e0Yre5i.png xscreensaver itself
