### ISSUE TITLE
Bugs when using dual monitors

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon-screensaver#28]
When using dual monitors I lock my screen and return to my normal desktop showing on the left screen and the lockscreen only on the right screen. The password dialogue box does not show up at all so to unlock my screen I have to type the password blindly and press enter.

**Comment by kehugter** [comment]
Can't reproduce and never had this issue

cinnamon-screensaver 2.6.4

**Comment by JosephMcc** [comment]
Can you still reproduce this on newer Cinnamon versions? It seems to work correctly here.

**Comment by kehugter** [comment]
Won't be able to check until July.

**Comment by JosephMcc** [comment]
Closing due to lack of response.
