### ISSUE TITLE
Computer is locked upon screensaver started or computer suspended

### ISSUE THREAD

**Issue by ralfeus** [linuxmint/cinnamon-screensaver#281]
```
 * Cinnamon-Screensaver version: 3.8.2
 * Distribution - Mint 19
 * Graphics hardware *and* driver used: 2nd Generation Core Processor Family Integrated Graphics Controller
 * 32 or 64 bit: 64 bit
 ```

**Issue**
Screensaver asks for a password regardless of whether it's enabled or not

**Steps to reproduce**
Open Screensaver settings
Disable "Lock the computer when put to sleep"
Disable "Lock the computer after the screensaver starts"
Wait for screensaver to start. Or put computer to sleep
Close screensaver. Or wake it up
Password is required.

**Expected behaviour**
The computer should not be locked. Closing screensaver (or waking up) should directly go to the desktop

**Other information**

**Comment by icarter09** [comment]
Cinnamon 3.8.9
Linux Mint 19 64bit

I went through the steps for this issue, but was not able to duplicate the problem. 

@ralfeus are you still experiencing this problem? If so, have you updated to the latest version of Cinnamon?

**Comment by ralfeus** [comment]
> @ralfeus are you still experiencing this problem? If so, have you updated to the latest version of Cinnamon or Cinnamon-screensaver?

Hi. I guess I don't as I can't remember last time I was prompted to enter the password
