### ISSUE TITLE
Crash in xapp_kbd_layout_controller_get_current_icon_name

### ISSUE THREAD

**Issue by Axel-Naumann** [linuxmint/cinnamon-screensaver#286]
```
 * cinnamon-screensaver 3.8.2
 * Distribution - Mint 19
 * GeForce GT 440, nvidia driver
 * 64 bit
 ```

**Issue**
cinnamon-screensaver crashes when "woken" up, i.e. when it should draw a box "enter your password". That allows everyone to unlock without password; I consider this a security issue.

According to gdb, the crash happens here:
```
Starting program: /usr/bin/python3
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebdbf700 (LWP 414)]
[New Thread 0x7fffeb5be700 (LWP 415)]
[New Thread 0x7fffeadbd700 (LWP 416)]
[New Thread 0x7fffea5bc700 (LWP 417)]
[New Thread 0x7fffe9dbb700 (LWP 418)]
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
Starting screensaver...
Not running under the session scope, trying XDG_SESSION_ID
found session: c2
Successfully using logind
[Thread 0x7fffe9dbb700 (LWP 418) exited]
[Thread 0x7fffeadbd700 (LWP 416) exited]
[New Thread 0x7fffeadbd700 (LWP 1673)]

Thread 1 "cinnamon-screen" received signal SIGSEGV, Segmentation fault.
0x00007fffd353392a in xapp_kbd_layout_controller_get_current_icon_name
() from /usr/lib/x86_64-linux-gnu/libxapp.so.1

(gdb) bt
#0  0x00007fffd353392a in xapp_kbd_layout_controller_get_current_icon_name ()
    at /usr/lib/x86_64-linux-gnu/libxapp.so.1
#1  0x00007ffff5bf2dae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007ffff5bf271f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007ffff65bedda in  () at /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
```

**Steps to reproduce**
`gdb --args python3 /usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py`
and move the mouse or hit any key.

**Expected behaviour**
Password UI appears, no crash.

**Other information**
Let me know what else to provide.
(This might be also causing https://github.com/linuxmint/cinnamon-screensaver/issues/280 )

**Comment by mtwebster** [comment]
Can you install the `libxapp-dbg` package.  It'd be even better if you could install `libgnomekbd8-dbgsym` as well, but you'd have to add some additional sources to apt (https://wiki.ubuntu.com/Debug%20Symbol%20Packages).  I'd settle for getting another trace the xapp debug symbols for the time being.

Do you have more than one keyboard layout installed?  Which ones are installed, specifically?

Can you try this script: https://github.com/linuxmint/xapps/blob/master/test-scripts/xapp-kbd-layout-controller

It's just a simple test window that lets you toggle different layouts (using the same api that cinnamon-screensaver uses) - this is probably simpler to test things with.  It's in python and you can just make it executable and run or run with python3, as you did when getting the trace already.

Does this happen simply by locking the screen and immediately trying to unlock?  It sounds like it, but I want to be sure - this doesn't just happen, for instance, when resuming from sleep, etc..

Thanks

**Comment by Axel-Naumann** [comment]
> Does this happen simply by locking the screen and immediately trying
to unlock?

Yes (where the "immediately" doesn't seem to be a required part of triggering the
crash). Any action (mouse, keyboard) that would usually cause the password UI to appear triggers it, before the password UI appears.

> Do you have more than one keyboard layout installed? Which ones are installed, specifically?

cinnamon-setting says my only keyboard layout is "English (US)".

> Can you try this script: https://github.com/linuxmint/xapps/blob/master/test-scripts/xapp-kbd-layout-controller

Sure, but:
```
$ python3 ./xapp-kbd-layout-controller
Traceback (most recent call last):
  File "./xapp-kbd-layout-controller", line 167, in <module>
    main = Main()
  File "./xapp-kbd-layout-controller", line 48, in __init__
    self.label.set_text(self.controller.get_current_name())
TypeError: Argument 1 does not allow None as a value
```

> Can you install the libxapp-dbg package. ... I'd settle for getting another trace the xapp debug symbols for the time being.

```
Thread 1 "cinnamon-screen" received signal SIGSEGV, Segmentation fault.
0x00007fffdb53392a in xapp_kbd_layout_controller_get_current_icon_name (controller=<optimized out>)
    at ../../libxapp/xapp-kbd-layout-controller.c:554
554     ../../libxapp/xapp-kbd-layout-controller.c: No such file or directory.
(gdb) bt
#0  0x00007fffdb53392a in xapp_kbd_layout_controller_get_current_icon_name (controller=<optimized out>)
    at ../../libxapp/xapp-kbd-layout-controller.c:554
#1  0x00007ffff5bf2dae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#2  0x00007ffff5bf271f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007ffff65bedda in  () at /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
#4  0x00007ffff65c09b8 in  () at /usr/lib/python3/dist-packages/gi/_gi.cpython-36m-x86_64-linux-gnu.so
```

Please let me know whether `libgnomekbd8-dbgsym` will help.

**Comment by mtwebster** [comment]
This doesn't make any sense - the code where it's crashing should never even be reached when a single layout is loaded.  Can you try adding an additional layout? (keyboard settings->layouts, + key in lower left corner) - then try both the screensaver and that script (it should work with 2 layouts).

Then go ahead and remove that layout you added, and try the screensaver again.

Thanks

**Comment by Axel-Naumann** [comment]
Yes that "fixes" the issue. But now I don't know how to help you debug the underlying problem :-) Thanks for fixing my machine, though!

**Comment by mtwebster** [comment]
Did you try removing the layout extra again after installing it?  And the issue did not return even with only the single layout again?

It is strange - maybe previously had you tried installing/removing layouts - it's possible there was some leftover bit of configuration in the underlying layout data.  That's really all I can think of that may have caused this.

Was this a clean install of Mint 19 or upgraded from 18?

**Comment by Axel-Naumann** [comment]
> And the issue did not return even with only the single layout again?

Correct: I removed the second layout; I restarted `cinnamon-screensaver` and it doesn't crash anymore.

> maybe previously had you tried installing/removing layouts

No.

> it's possible there was some leftover bit of configuration in the underlying layout data

Unlikely; it was a rather fresh install (couple of days old) and I never messed with the layouts.

> Was this a clean install of Mint 19

Clean install.

Anyway, I suggest you close this, and if someone else runs into this you now have more background info to debug their case.

Thanks for your help!
