### ISSUE TITLE
pam_ecryptfs: seteuid error

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/cinnamon-screensaver#289]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 3.8.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19
 ```

**Issue**

Syslog: 'cinnamon-screensaver-pam-helper // pam_ecryptfs: seteuid error'.

**Steps to reproduce**

Unknown. Possibly, just let the screensaver come on.

**Expected behaviour**

I expect to see no such error in the log. Possibly too this error relates to other bugs filed on this tracker.

**Other information**

The same error message has been reported to Debian [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=704865), with this text:

> This error seems to affect many other people and in different
> settings, although most are screensaver-related, but the root cause
> may not be the screensaver itself

As that bug report notes, the same problem is reported [here](https://bugs.launchpad.net/ubuntu/+source/gnome-screensaver/+bug/1085706) with Ubuntu too, and marked as affecting sixty-eight people.

Does the problem owe to the screensaver? If it doe not, should the screensaver work around it?

I used to use ecryptfs but I am not anymore (and yet I still see the error).

**Comment by kikoucalou** [comment]
Same on Linux Mint19 :
cinnamon-screensaver-pam-helper: pam_ecryptfs: seteuid error

**Comment by kambizaf** [comment]
Same issue on Linux Mint on Thinkpad X1 Extreme 
`Sep 29 15:52:49 X1Extreme cinnamon-screensaver-pam-helper[5818]: pam_ecryptfs: seteuid error`

**Comment by Harry-W-Haines-III** [comment]
Also present with Mint 19.1 Beta.
Dec  4 15:12:23 front-office cinnamon-screensaver-pam-helper: pam_ecryptfs: seteuid error
Seen on wake up from suspend.
