### ISSUE TITLE
Unable to enter password after changes to PAM stack

### ISSUE THREAD

**Issue by conkeating** [linuxmint/cinnamon-screensaver#290]
```
 * Cinnamon-Screensaver version 3.8.2
 * Distribution - Arch 
 * Radeon RX460/ amdgpu & mesa-git 
 * 64-bit
 ```

**Issue**
Attempting to modify the PAM stack for cinnamon-screensaver results in repeated "password incorrect" errors, even if the system is not interacted with in any way. Too short of a time in between errors to input full PIN.

**Steps to reproduce**
Replace `auth include system-auth` with alternative authentication method ([libpam-pwdfile](https://github.com/tiwe-de/libpam-pwdfile) in my case) in cinnamon-screensaver PAM stack.

**Expected behaviour**
cinnamon-screensaver should wait until user has finished inputting password to check against appropriate method.

**Other information**
https://ptpb.pw/8GEe - Pastebin of `cat lightdm cinnamon-screensaver`

**Comment by conkeating** [comment]
Running cinnamon-screensaver with the debug flag shows what looks to be the issue 
```
pam_start("cinnamon-screensaver", "cmk", ...) ==> 0 (Success)
   pam_authenticate (...) ==> 9 (Authentication service cannot retrieve authentication info)
 pam_end (...) ==> 0 (Success)
Verify user returned: FALSE
Authentication failed, retrying
```

**Comment by leigh123linux** [comment]
What are the perms  for  /etc/pin ?
Maybe try

```
sudo chmod 644 /etc/pin
```

**Comment by conkeating** [comment]
@leigh123linux that seems to have done the trick. I had it set to 600, the same as /etc/shadow. While I'm not 100% sure, I do seem to recall having it set to 600 on a previous setup with the same configuration and it working just fine.

**Comment by leigh123linux** [comment]
cinnamon-screensaver and most other screensavers  processes run as user so wouldn't be able to read /etc/pin with 600 perms.
Lightdm process has root perms so is able to read it.

see this report

https://github.com/tiwe-de/libpam-pwdfile/issues/3

**Comment by leigh123linux** [comment]
Maybe it's worth checking /sbin/unix_chkpwd perms

https://unix.stackexchange.com/questions/422411/pam-authentication-failure-with-valid-password

**Comment by conkeating** [comment]
D'oh! Well now I feel silly. That definitely makes sense. I had assumed since the actual `crypt`'ing of the password was done by PAM itself that it would necessarily have been run as root so as to have been able to check /etc/shadow.

**Comment by conkeating** [comment]
I also seem to have some hazy recollections of enabling cinnamon-screensaver as a systemd service, which could also explain why there were no issues with 600 for perms.
