### ISSUE TITLE
IBus injects and prevent cinnamon-screensaver from unlocking

### ISSUE THREAD

**Issue by minhducsun2002** [linuxmint/cinnamon-screensaver#297]
```
 * Cinnamon-Screensaver version : `cinnamon-screensaver 3.8.2`
 * Distribution : Debian Stretch with `buster` and `sid` repository on `amd64`
 * Graphics hardware : Intel HD Graphics 3000 (integrated)
   * Driver : Mesa DRI Intel Sandybridge Mobile
     (3.0 Mesa 18.2.5 as detected from `hardinfo`)
```

**Issue**

`cinnamon-screensaver` picks up keyboard input from Ibus, leading to inability of entering the password due to pre-edit mechanism

**Steps to reproduce**
1. Lock the screen as usual, either by invoking `cinnamon-screensaver`/`cinnamon-screensaver-command`, or through the Lock button of Cinnamon Menu
2. The screen gets locked. Enter the password as usual.
  2.1 During entering the password, the text appears *in plaintext* due to IBus's pre-edit mechanism being active. Pressing Enter finishes typing and start the authentication, but before that, the password field is cleared, so an empty password was sent to verification, not the one inputted.

**Expected behaviour**

The screen-lock correctly verifies the password and restore usual Cinnamon environment.

**Comment by clefebvre** [comment]
Is this still an issue nowadays? If so we might need to disable IM?

**Comment by minhducsun2002** [comment]
I have moved to another DE a year ago, so what I reported here might not be relevant anymore. I'll close this issue, feel free to reopen it as you see it.
