### ISSUE TITLE
100% CPU usage when media controls are shown

### ISSUE THREAD

**Issue by bastimeyer** [linuxmint/cinnamon-screensaver#299]
```
 * Cinnamon-Screensaver version: cinnamon-screensaver 4.0.1-1
 * Distribution: Arch
 * Graphics hardware *and* driver used: nvidia-390xx-dkms 390.87-15
 * 64 bit
 ```

**Issue**

I can observe 100% CPU usage of the `cinnamon-screensaver` process while being logged in via ssh on my system from another machine. This does only happen when the media controls are being shown.

**Steps to reproduce**

```bash
# start a supported media player with the necessary dbus interface, eg. Clementine
clementine --play &
# lock the screen and observe 100% CPU usage
cinnamon-screensaver-command --lock
```

**Other information**

```
$ xrandr | grep 'Screen 0'
Screen 0: minimum 8 x 8, current 3840 x 1080, maximum 16384 x 16384
```

**Comment by paranoidi** [comment]
`
[Mon Jul 29 12:20:09 2019] CPU5: Package temperature/speed normal
[Mon Jul 29 12:20:09 2019] CPU7: Package temperature/speed normal
[Mon Jul 29 12:28:23 2019] CPU6: Core temperature above threshold, cpu clock throttled (total events = 79)
[Mon Jul 29 12:28:23 2019] CPU2: Core temperature above threshold, cpu clock throttled (total events = 79)
[Mon Jul 29 12:28:23 2019] CPU2: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU6: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU0: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU1: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU5: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU4: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU3: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU7: Package temperature above threshold, cpu clock throttled (total events = 89)
[Mon Jul 29 12:28:23 2019] CPU6: Core temperature/speed normal
[Mon Jul 29 12:28:23 2019] CPU0: Package temperature/speed normal
[Mon Jul 29 12:28:23 2019] CPU2: Core temperature/speed normal
[Mon Jul 29 12:28:23 2019] CPU4: Package temperature/speed normal
`

I was AFK from computer, it was locked and did was not doing anything really. High CPU usage is observed with screensaver regardless of situation. The more problematic is that it also has crashed about 30% of time when I return to my workstation. (#263)
