### ISSUE TITLE
Album art cropped when I lock the screen

### ISSUE THREAD

**Issue by zignd** [linuxmint/cinnamon-screensaver#300]
```
 * Cinnamon-Screensaver version: 3.8.2
 * Distribution: Linux Mint 19 Tara
 * Graphics Card: Intel Corporation HD Graphics 620
 * 64 bit
 ```

**Issue**

I believe Cinnamon Screensaver is misbehaving for me when I'm playing a song and it shows the album art. would anyone mind confirming if the same happens on a larger display? Here are a few "screen-photographs" to illustrate what I mean.

https://imgur.com/a/PGN3qn1

As can be seen, it crops part of the album art.

**Steps to reproduce**

Play a song on Spotify for example, lock the screen, get into the state in which you can see a text box to type your password, you're expected to see the album art at the right side of the password text box, the bottom of the album art will be cropped.

**Expected behaviour**

The album art should not be cropped.

**Comment by mtwebster** [comment]
What's the resolution of the monitor you're using here?  If it's hi-res, are you running it in hidpi? (cinnamon-settings->general->user interface scale)

**Comment by zignd** [comment]
It's 1366x768 (16:9) on a laptop and the interface scaling is set to Auto, but there's no difference when I set it to Normal, therefore, I believe it's being automatically set to Normal. When I set it to Double (Hi-DPI) there's a difference, possibly confirming that it is not using this setting.

**Comment by mtwebster** [comment]
Ok the low resolution is the issue (our issue not yours :)) I'll see if we can be a little smarter about keeping sizes down in these cases (for the clock as well, I would imagine that looks bad occasionally as well, depending on how you have it configured).

**Comment by zignd** [comment]
Thank you! That was kinda quick! Do you have any idea about when will the next release be? At least for my version of the distro (Tara)?

**Comment by NikoKrause** [comment]
Mint 19.1 Tessa is currently in BETA. So the stable release will probably be at the end of this month.
