### ISSUE TITLE
Screensaver unresponsive when it activates

### ISSUE THREAD

**Issue by Blinkenn** [linuxmint/cinnamon-screensaver#304]
```
 * Cinnamon-Screensaver version 4.0.3
 * Distribution - LMDE3 
 * Virtualbox 5.2.24 with Guest additions installed
 * 64 bit
 ```

**Issue**
When screen saver starts it looks like it just shows the desktop (screen does not go black or show the login screen), cannot click on anything, and there isn't a login screen.
As it locks the VM, keyboard or mouse activity is not showing the login box. 
Have to hit Host-H (right control+H) to force an ACPI shutdown that then shows the login screen where you can enter your password blindly as there is still no mouse or key-type activity happening on screen.

**Steps to reproduce**
Brand new LMDE install in a Virtualbox 5.2.24 guest, Guest additions installed and rebooted, fully updated LMDE3 and reboot, activate screensaver from start menu and issue appears.

**Expected behaviour**
Screensaver activates, turns screen black and shows a login screen when mouse or keyboard is used

**Other information**

**Comment by 4f96a64d** [comment]
* Cinnamon-Screensaver version 4.0.3
 * Distribution - LMDE3 
 * Virtualbox 5.2.30 with Guest additions installed
 * 64 bit

@Blinkenn 

- Can you confirm whether you can blindly type your password to unlock the screen without Host-H?
- Also, if you have a shell or other window open, does it disappear when you lock the screen?

The issue I have is similar to yours but I have observed these additional behaviours:

1. Locking from the start menu, windows disappear from the desktop, the mouse cursor still moves but can't interact with the desktop but changes to the text bar where the password entry field would be, typing the password unlocks the desktop and windows re-appear.
2. Using <ctrl><alt><l> when a window other than the desktop is active the lock screen may appear with the clock but will remain static, never updating. Other times the same behaviour as 1. is seen. Blindly entering the password unlocks the desktop as in 1

Seems to be that the screen never refreshes when the screensaver is active.

**Comment by 4f96a64d** [comment]
Unchecking "Use 3D Acceleration" seems to fix this for me.

@Blinkenn Can you confirm if that works for you?

Perhaps this is a similar race condition as mentioned in #219

**Comment by Blinkenn** [comment]
unchecking Use 3D Acceleration works but is not optimal. 
Issue present in 5.2.30. Hitting Control-H (host shutdown signal) allows blind entry of the password with the power dialog present after unlocking.

**Comment by paranoidi** [comment]
Screensaver is unstable even with real hardware, might not be always be VirtualBox related.

**Comment by smurphos** [comment]
Use a newer version of Virtualbox and the VMSVGA video driver.

**Comment by clefebvre** [comment]
Inactive issue, closing.
