### ISSUE TITLE
How could I use webkit plugin in ArchLinux

### ISSUE THREAD

**Issue by colinaaa** [linuxmint/cinnamon-screensaver#308]
```
 * Cinnamon-Screensaver version 4.0.3(cinnamon-screensaver --version)
 * Distribution - Arch (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used never mind
 * 32 or 64 bit
 ```

**Issue**

I want to use webkit to customize my lock screen, but there is no package for Arch to use webkit plugin.

**Steps to reproduce**

I looked up to `/usr/share/cinnamon-screensaver` and nothing has been found about webkit.

```shell
ls /usr/share/cinnamon-screensaver
albumArt.py                      cinnamon-screensaver-gtk3.14.css  clock.py      floating.py   monitorView.py    __pycache__    status.py         widgets
audioPanel.py                    cinnamon-screensaver-gtk3.18.css  config.py     infoPanel.py  pamhelper         service.py     unlock.py
baseWindow.py                    cinnamon-screensaver-gtk3.20.css  constants.py  __init__.py   passwordEntry.py  singletons.py  util
cinnamon-screensaver-command.py  cinnamon-screensaver-main.py      dbusdepot     manager.py    playerControl.py  stage.py       volumeControl.py
```

**Expected behaviour**

Just tell me how to enable webkit is fine.
Thanks in advanced.

**Other information**

I'm using Cinnamon 4.0.10 and lightdm.

**Comment by JosephMcc** [comment]
You cannot. Support for this and xscreensaver was removed prior to the 4.0 release.

https://github.com/linuxmint/cinnamon-screensaver/commit/081ba50b39bcbf5f8ef58c6c6b76d3e385d48db1
