### ISSUE TITLE
[Feature Request] Make on-screen keyboard optional

### ISSUE THREAD

**Issue by dqgls** [linuxmint/cinnamon-screensaver#313]
I'm running `cinnamon-screensaver 4.2.0` (LM 19.2 beta) which introduced on-screen keyboard widget. However when unneeded it seems to only confuse users. I suggest this widget is made optional - just like album art for example, which can be toggled in the screensaver settings.

**Comment by mtwebster** [comment]
I don't understand - the icon at the bottom of the screen to activate the keyboard is confusing?

Or is the keyboard itself appearing when you go to unlock?
