### ISSUE TITLE
Lock-screen password echoing is very laggy

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-screensaver#314]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 4.2.0
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 19.2
 * Graphics hardware *and* driver used: Intel UHD Graphics 620; 3.0 Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

When I enter my password, the lock screen shows characters - well, asterisks - very slowly.

**Steps to reproduce**

The problem is intermittent.

**Expected behaviour**

Characters should echo to the screen at the normal speed.

**Other information**

Cf. https://github.com/linuxmint/alpha-testing/issues/10
Cf. https://github.com/linuxmint/cinnamon-screensaver/issues/285?

**Comment by unixtam** [comment]
Same issue here since recent upgrade to Mint 19.2. It's just the visual feedback that seems to be lagging behind. Key strikes are registered and processed at normal speed.

**Comment by LinuxOnTheDesktop** [comment]
Alt-tab 'coverflow 3d' is slow too, unfortunately - at least on my system (and admittedly the problems may be unrelated).

**Comment by catthou** [comment]
I also have this problem since upgrading to Mint 19.2, using cinnamon screensaver 4.2.

I don't get the problem when I manually invoke the lock screen vit hotkey; but it's _super_ laggy when it auto-locks after 5 minutes of inactivity.

My screensaver settings are:
- After 10 minutes of activity, start the screensaver
- Screen turns off at this point as well, per power savings settings
- After anohter 3 minutes, lock the screensaver requiring password to unlock

It may have something to do with the screen turning off, or specifically when locking after

**Comment by rschouwenburg** [comment]
I echo this problem. Mint 19.2 and cinnamon screensaver 4.2. It only happens on my desktop (Nvidia) and not on my laptop (Intel).

The feedback of the password dialog is super slow. When I just type blind, I can still unlock the screen as usual. There's simply no indication I typed something.

Let me know if I can help test or analyze something.

**Comment by Hilyxx** [comment]
Same problem here. Password dialog and media key are slow and irresponsive after 5-10 minutes of inactivity with this screensaver version. 

Linux mint 19.2
cinnamon 4.2
Intel graphic HD 4000

**Comment by mtwebster** [comment]
Anyone that's experiencing it, do you have your power management to turn the monitor off after a time?

If that's so, does this problem occur only when coming from locked/monitor off?  Or simply locked, regardless of the monitor state?

I've actually been observing and trying to get to the bottom of this for some time, these things seem to be related, I just want to get more observations.  Thanks

**Comment by catthou** [comment]
> Anyone that's experiencing it, do you have your power management to turn the monitor off after a time?
I set my lock screen timer to 3 minutes and power managerment to 5 minutes and after multiple trials it seems to reliably lag only after power management kicks in, and never if I manually lock it via hotkey or if it auto-locks on timeout, without the screen going off.

I'm using a GTX 550 Ti with nvidia proprietary driver version 390.116 (the latest for my card) if that plays any role.

**Comment by LinuxOnTheDesktop** [comment]
> do you have your power management to turn the monitor off after a time?

Yes.

> If that's so, does this problem occur only when coming from locked/monitor off? Or simply locked, regardless of the monitor state?

I have tested just now - twice - with the following result. When the monitor is locked but on, then there is no delay in echoing keys the screen.

**Comment by rschouwenburg** [comment]
> Anyone that's experiencing it, do you have your power management to turn the monitor off after a time?

Yes

> If that's so, does this problem occur only when coming from locked/monitor off? Or simply locked, regardless of the monitor state?

No, when it is locked and the screen is active, there is no problem for me.

When the monitor goes to sleep after it is locked, there is no problem for the first 10-15m.

After the monitor is sleeping for 10-15m or more, I see this problem.

The timings are just estimates.

I have never seen this problem on my laptop. Here the screen is locked when it suspends.

**Comment by unixtam** [comment]
@mtwebster, I have been observing this for the past couple of days and lagging seemed to only ever occur after power management had turned the screen off, matching your observations.

**Comment by NathanaelA** [comment]
More data; seems to be only 19.2; and probably power saving mode in my case also.
 If I click the "Person" button to return to the main login screen from the lock screen the input starts working again for me.

**Comment by mrdumpty** [comment]
Same here, it happens only when monitor was automatically powered down.

**Comment by jasonoverland** [comment]
This started happening to me after upgrading to 19.2. Using a GTX 1060 3gb with NVidia drivers. I have not changed any power settings.

**Comment by LiohMoeller** [comment]
After changing both, screenlocker and engery sever options to the same time (e.g. 15min) the issue did not occur again.

**Comment by mtwebster** [comment]
Can you guys try the packages I posted here: https://github.com/linuxmint/muffin/issues/530#issuecomment-563476189

This fixes the issue for me.

**Comment by LinuxOnTheDesktop** [comment]
I have installed those packages, but the problem is intermittent on my system so it will take me a while to give a report.

**Comment by Leopard1907** [comment]
This problem exists on my end too. But i can only repro it when pc downloads some stuff in the background and locked the screen itself after awhile.

Otherwise it doesn"t exist.

Steps to repro : Download something in the background and leave pc screen open. Preferably a big Steam game.

**Comment by catthou** [comment]
Using the muffin you linked resolves the issue for me. However it makes the font in the "Enter your password" box hideous for some reason, and the dots that represent my password are all smooshed together.

```
$ cinnamon --version
Cinnamon 4.2.4
```

```
$ muffin --version
muffin 4.4.1
```

**Comment by LinuxOnTheDesktop** [comment]
I think I may have experienced the problem just now on Mint 19.3. I wonder whether the problem has to do with the power-off dialogue - which, on my system, is set to count down - running in the background (such that it is revealed once one does manage to unlock the PC).
