### ISSUE TITLE
cinnamon-screensaver is started in XFCE session

### ISSUE THREAD

**Issue by mabod** [linuxmint/cinnamon-screensaver#319]
```
 * cinnamon-screensaver 4.2.0
 * Manjaro Stable
 ```

**Issue**

cinnamon-screensaver is started in  XFCE session:
```
5# ps -ef | grep screen 
matthias  5902  1135  0 11:27 ?        00:00:00 cinnamon-screensaver
matthias  5981  5876  0 11:27 ?        00:00:00 xfce4-screensaver
```
I see that dbus-daemon is starting it:

`
Aug 23 10:38:02 leno dbus-daemon[1161]: [session uid=1000 pid=1161] Successfully activated service 'org.cinnamon.ScreenSaver'`

```
9# cat /usr/share/dbus-1/services/org.cinnamon.ScreenSaver.service
[D-BUS Service]
Name=org.cinnamon.ScreenSaver
Exec=/usr/bin/cinnamon-screensaver
```

How can I prevent the start in XFCE sessions?

**Comment by mabod** [comment]
This issue is clearly dbus related.

If I run `systemctl status --user` I see that dbus starts the screensaver even in the XFCE environment:

```
...
      ├─dbus.service
           │ ├─ 1161 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd->
           │ ├─ 1196 /usr/lib/xfce4/xfconf/xfconfd
           │ ├─ 1365 /usr/lib/goa-daemon
           │ ├─ 1375 /usr/lib/goa-identity-service
           │ ├─ 1418 /usr/lib/dconf-service
           │ ├─ 6860 /usr/bin/gnome-keyring-daemon --start --foreground --components=secrets
           │ ├─ 9819 /usr/lib/tumbler-1/tumblerd
           │ └─10372 cinnamon-screensaver
...
```
And when I move
`/usr/share/dbus-1/services/org.cinnamon.ScreenSaver.service`
out of the way, the screensaver is not starting in XFCE.

**Comment by leigh123linux** [comment]
Please file the issue against XFCE as they will need to add a blacklist to prevent is starting in their session.
Cinnamon had to do the same to prevent gnome-screensaver from starting in cinnamon session.
