### ISSUE TITLE
[HOW] to build the cinnamon screensaver?

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/cinnamon-screensaver#322]
I have a problem with build this app in GNOME Builder, logs are here: https://pastebin.com/BKTaQF0R

Teoretycly i have all libs so this app should build without problems.
Do you have any idea?

PS: @mtwebster  sorry for this question but i am new.
![Screenshot from 2019-10-10 23-25-24](https://user-images.githubusercontent.com/23406555/66608180-365ab400-ebb6-11e9-9607-220c4c433496.png)

**Comment by mtwebster** [comment]
I've never used gnome builder at all, so I can't help you there, but depending on what distro you're on, it's relatively simple:

If you're on Ubuntu, Mint or Debian (or anything else that might use deb/apt packaging) you can simply clone this repo, then enter the folder and run:

```
dpkg-buildpackage
```
You can do -j2 or -j4 to have it build more quickly, but it doesn't take too long anyhow.  Once that completes, go back one folder, and install all the deb packages:
```
sudo apt-get install *.deb
```

On other distros, if you want to build from the repo, again, clone it, then:
```
./autogen.sh --prefix=/usr
...
...
# if that completes without error, 
make (-j4 or whatever)
```
then to install,
```
sudo make install
```

I need to add this to the HACKING file, sorry.

**Comment by pyroxar** [comment]
I am sorry but how I can biuld this? https://github.com/linuxmint/gnome-screenshot

Autogen,sh and make doesn't work, I fight now with meson and ninja
