### ISSUE TITLE
Cinnamon-Screensaver - DeprecationWarning: Gtk.icon_size_register is deprecated

### ISSUE THREAD

**Issue by Padre2** [linuxmint/cinnamon-screensaver#326]
```
 * Cinnamon-Screensaver version 4.4.0
 * Distribution - Arch 4.4
 * Graphics hardware AMD/ATI Radeon
 * 64 bit
 ```

**Issue**
.Xsession-errors
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:61: DeprecationWarning: Gtk.icon_size_register is deprecated
  Gtk.icon_size_register("audio-button", 20, 20)

**Steps to reproduce**
Every start-up

**Expected behaviour**

**Other information**

**Comment by claudiux** [comment]
The line 61 of `/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py` seems to be useless. The "audio-button" icon does not exist in themes Adwaita, Mint-X, Mint-Y.

Maybe remove this line? The screen saver works perfectly without it, even when music is played.

**Comment by Padre2** [comment]
@claudiux  Yes, in fact I could not understand the need for this line and had already deleted it, which solved the deprecation notice issue.  However, I was not sure if there might be other effects. 
Does this require a PR? Presumably it will still be in the next version, unless removed.

**Comment by claudiux** [comment]
@Padre2 I just did this PR.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/blob/master/src/playerControl.py#L32
