### ISSUE TITLE
Lock-screen totally black after turn on computer

### ISSUE THREAD

**Issue by denihs** [linuxmint/cinnamon-screensaver#334]
I just install the linux Mint 19.3 (with Cinnamon 4.4.8) and everything is in the latest version. The problem showed up since the first reboot, the lock screen is shown totally black. Luckily I'm still able to enter with the password which makes the system start normally, but this error is pretty annoying and I have no idea how to fix it.

**Comment by leigh123linux** [comment]
Without logs this issue wont be investigated.

**Comment by denihs** [comment]
I'm not sure which log to send here, but below are the .xsession-errors logs:

dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting XAUTHORITY=/home/denyhs/.Xauthority
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting LC_MEASUREMENT=pt_BR.UTF-8
dbus-update-activation-environment: setting LC_PAPER=pt_BR.UTF-8
dbus-update-activation-environment: setting LC_MONETARY=pt_BR.UTF-8
dbus-update-activation-environment: setting LANG=en_US.UTF-8
dbus-update-activation-environment: setting GDM_LANG=en_US
dbus-update-activation-environment: setting DISPLAY=:0
dbus-update-activation-environment: setting MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
dbus-update-activation-environment: setting LC_NAME=pt_BR.UTF-8
dbus-update-activation-environment: setting XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/denyhs
dbus-update-activation-environment: setting USER=denyhs
dbus-update-activation-environment: setting DESKTOP_SESSION=cinnamon
dbus-update-activation-environment: setting DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
dbus-update-activation-environment: setting PWD=/home/denyhs
dbus-update-activation-environment: setting HOME=/home/denyhs
dbus-update-activation-environment: setting QT_ACCESSIBILITY=1
dbus-update-activation-environment: setting XDG_SESSION_TYPE=x11
dbus-update-activation-environment: setting XDG_DATA_DIRS=/usr/share/cinnamon:/usr/share/gnome:/home/denyhs/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
dbus-update-activation-environment: setting XDG_SESSION_DESKTOP=cinnamon
dbus-update-activation-environment: setting LC_ADDRESS=pt_BR.UTF-8
dbus-update-activation-environment: setting LC_NUMERIC=pt_BR.UTF-8
dbus-update-activation-environment: setting GTK_MODULES=gail:atk-bridge
dbus-update-activation-environment: setting SHELL=/usr/bin/zsh
dbus-update-activation-environment: setting XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
dbus-update-activation-environment: setting IM_CONFIG_PHASE=1
dbus-update-activation-environment: setting GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
dbus-update-activation-environment: setting SHLVL=1
dbus-update-activation-environment: setting LANGUAGE=en_US
dbus-update-activation-environment: setting LC_TELEPHONE=pt_BR.UTF-8
dbus-update-activation-environment: setting GDMSESSION=cinnamon
dbus-update-activation-environment: setting LOGNAME=denyhs
dbus-update-activation-environment: setting DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
dbus-update-activation-environment: setting XDG_RUNTIME_DIR=/run/user/1000
dbus-update-activation-environment: setting XAUTHORITY=/home/denyhs/.Xauthority
dbus-update-activation-environment: setting XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
dbus-update-activation-environment: setting XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon:/etc/xdg
dbus-update-activation-environment: setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
dbus-update-activation-environment: setting LC_IDENTIFICATION=pt_BR.UTF-8
dbus-update-activation-environment: setting _=/usr/bin/dbus-update-activation-environment
Clutter-Message: 07:29:08.511: Sync method: PRESENTATION TIME
Cjs-Message: 07:29:09.249: JS LOG: About to start Cinnamon
Cjs-Message: 07:29:09.336: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 84 ms
Cjs-Message: 07:29:09.347: JS LOG: [LookingGlass/info] loading user theme: /usr/share/themes/Mint-Y-Dark/cinnamon/cinnamon.css
Cjs-Message: 07:29:09.374: JS LOG: [LookingGlass/info] added icon directory: /usr/share/themes/Mint-Y-Dark/cinnamon
** Message: 07:29:09.482: nemo-desktop: session is cinnamon, establishing proxy
Cjs-Message: 07:29:09.579: JS LOG: [LookingGlass/info] PlacesManager: Updating devices
Cjs-Message: 07:29:09.595: JS LOG: [LookingGlass/info] loaded at Thu Feb 27 2020 07:29:09 GMT-0400
Cjs-Message: 07:29:09.595: JS LOG: Cinnamon started at Thu Feb 27 2020 07:29:09 GMT-0400
Cjs-Message: 07:29:09.641: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Cjs-Message: 07:29:09.641: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Cjs-Message: 07:29:09.641: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: 07:29:10.278: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 254 ms
Cjs-Message: 07:29:10.303: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 24 ms
Cjs-Message: 07:29:10.365: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 62 ms
Cjs-Message: 07:29:10.373: JS LOG: [LookingGlass/info] Role locked: tray
Cjs-Message: 07:29:10.378: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 12 ms
St-Message: 07:29:10.387: cogl npot texture sizes SUPPORTED
Cjs-Message: 07:29:10.398: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 20 ms
Cjs-Message: 07:29:10.411: JS LOG: [LookingGlass/info] Role locked: notifications
Cjs-Message: 07:29:10.422: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 24 ms
Cjs-Message: 07:29:10.454: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 30 ms
Cjs-Message: 07:29:10.486: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 32 ms
Cjs-Message: 07:29:10.527: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 40 ms
Cjs-Message: 07:29:10.577: JS LOG: [LookingGlass/info] Role locked: panellauncher
Cjs-Message: 07:29:10.606: JS LOG: [LookingGlass/info] Loaded applet grouped-window-list@cinnamon.org in 80 ms
Cjs-Message: 07:29:10.785: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 178 ms
Cjs-Message: 07:29:10.788: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nm-applet (org.x.StatusIcon.PID-1577-0)
Cjs-Message: 07:29:10.870: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet (org.x.StatusIcon.PID-1577-0)
Cjs-Message: 07:29:10.894: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 108 ms
Cjs-Message: 07:29:11.051: JS LOG: Unknown network device type, is 14
Cjs-Message: 07:29:11.492: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 598 ms
Cjs-Message: 07:29:11.492: JS LOG: [LookingGlass/info] AppletManager started in 1898 ms
Cjs-Message: 07:29:11.495: JS LOG: [LookingGlass/info] Cinnamon took 2246 ms to start
Cjs-Message: 07:29:14.351: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueberry (org.x.StatusIcon.PID-1675-0)
cinnamon-session[1272]: WARNING: t+9,20545s: Detected that screensaver has appeared on the bus
[0227/072920.678650:ERROR:main_delegate.cc(853)] Could not load cef_100_percent.pak
[0227/072920.684519:ERROR:main_delegate.cc(862)] Could not load cef_200_percent.pak
[0227/072920.797950:INFO:HandlerRendererProcess.cpp(6)] HandlerRendererProcess created
[0227/072920.808665:ERROR:main_delegate.cc(853)] Could not load cef_100_percent.pak
[0227/072920.808789:ERROR:main_delegate.cc(862)] Could not load cef_200_percent.pak
[0227/072921.562070:INFO:HandlerRendererProcess.cpp(6)] HandlerRendererProcess created
[0227/072921.566239:ERROR:main_delegate.cc(853)] Could not load cef_100_percent.pak
[0227/072921.566354:ERROR:main_delegate.cc(862)] Could not load cef_200_percent.pak
[0227/072921.702655:ERROR:gl_implementation.cc(280)] Failed to load /tmp/.mount_jetbrab5aDfK/usr/share/jetbrains-toolbox/swiftshader/libGLESv2.so: /tmp/.mount_jetbrab5aDfK/usr/share/jetbrains-toolbox/swiftshader/libGLESv2.so: cannot open shared object file: No such file or directory
[0227/072921.757582:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[0227/072921.778762:INFO:HandlerRendererProcess.cpp(10)] HandlerRendererProcess disposed
[0227/072921.781711:WARNING:gpu_process_host.cc(1205)] The GPU process has crashed 1 time(s)
[0227/072922.813853:INFO:HandlerRendererProcess.cpp(15)] Started CEF-render process
Cjs-Message: 07:29:22.913: JS LOG: [LookingGlass/info] Adding systray: toolbox (24x24px)
Cjs-Message: 07:29:22.915: JS LOG: [LookingGlass/info] Resized toolbox with normalized size (24x24px)
[0227/072923.336957:INFO:HandlerRendererProcess.cpp(6)] HandlerRendererProcess created
[0227/072923.339907:ERROR:main_delegate.cc(853)] Could not load cef_100_percent.pak
[0227/072923.340033:ERROR:main_delegate.cc(862)] Could not load cef_200_percent.pak
[0227/072923.355635:WARNING:gpu_process_host.cc(982)] Reinitialized the GPU process after a crash. The reported initialization time was 0 ms
[0227/072923.854538:INFO:CONSOLE(66)] "Updated model size: 316086", source: qrc://ui/index.js (66)
[0227/072923.899804:INFO:CONSOLE(66)] "Initial model size: 316051", source: qrc://ui/index.js (66)
[0227/072923.904647:INFO:CONSOLE(29)] "`size`, `width` and `height` props are not recommended to use in Ring UI `Icon` component. The intrinsic sizes of SVG icon (`width` and `height` SVG attributes) are used instead.

**Comment by mtwebster** [comment]
Is the monitor actually showing as 'awake' when this happens?  (usually the power indicator changes color) or is this happening even if the screensaver activates temporarily?  While the screensaver is 'active' (no lock screen) does it appear normally, with the clock and desktop background?

Can you kill the screensaver (`cinnamon-screensaver-command -e`) and then restart it with logging? (`cinnamon-screensaver --debug`)

Can you run `inxi -F` also

What gtk theme are you running? (cinnamon-settings->themes->controls) - if not a mint theme can you try with one?  This is unlikely to affect anything but may as well rule it out.

**Comment by denihs** [comment]
**Is the monitor actually showing as 'awake' when this happens?** Actually it does not... seems like the monitor is shut down.

**While the screensaver is 'active' (no lock screen) does it appear normally, with the clock and desktop background?** Yes

**cinnamon-screensaver --debug**
Debug mode active
/usr/share/cinnamon-screensaver/cinnamon-screensaver-main.py:84: Warning: g_base64_encode_step: assertion 'in != NULL' failed
  css = provider.to_string()
Cinnamon Screensaver support not found in current theme - adding some...
Trying to connect to logind...
org.gnome.ScreenSaver is gone from the session bus
org.mate.ScreenSaver is gone from the session bus
Starting screensaver...
Not running under the session scope, trying XDG_SESSION_ID
found session: c2
Successfully using logind
Found 2 Xinerama screens on display :0
Monitor 0 is 0,0 1920 x 1080
Monitor 1 is 1920,0 1366 x 768
Cinnamon Screensaver compiled without Solaris Xinerama support
Scale factor of 1 applied.  Monitor 0 is 0,0 1920 x 1080
Scale factor of 1 applied.  Monitor 1 is 1920,0 1366 x 768
Narrowest monitor width after scaling (1366x768) is below threshold of 1200x1000, applying low-res mode
Stage.update_geometry - new backdrop position: 0, 0  new size: 3286 x 1080
powerWidget: Updating battery info: /org/freedesktop/UPower/devices/battery_BAT0 - icon: battery-full-charged-symbolic - percentage: 100.0
manager: locking after delay ('lock-delay')
manager: user activity, waking
authClient: attempting to initialize
authClient: initialized
manager: locked, raising unlock widget
powerWidget: Updating battery info: /org/freedesktop/UPower/devices/battery_BAT0 - icon: battery-full-charged-symbolic - percentage: 100.0
pam_start ("cinnamon-screensaver", "denyhs", ...) ==> 0 (Success)
Handling message style 1: 'Password: '
Waiting for respose to message style 1: 'Password: '
Waiting for lock
Waiting for response
Got message style 1: 'Password: '
Output from pam helper: 'CS_PAM_AUTH_SET_PROMPT_Password: _'
authClient: idle add auth-prompt
Output from pam helper: 'CS_PAM_AUTH_BUSY_FALSE'
authClient: idle add auth-busy
Output from pam helper: ''
authClient: message to child
auth_message_handler processing response string
should interrupt: 0
Got response
Got respose to message style 1: interrupt:0
Msg handler returned 1
Output from pam helper: 'CS_PAM_AUTH_BUSY_TRUE'
authClient: idle add auth-busy
Output from pam helper: ''
   pam_authenticate (...) ==> 0 (Success)
pam_acct_mgmt (...) ==> 0 (Success)
   pam_setcred (...) ==> 0 (Success)
 pam_end (...) ==> 0 (Success)
Verify user returned: TRUE
Output from pam helper: 'CS_PAM_AUTH_SUCCESS'
authClient: idle add success
Output from pam helper: ''
authClient: helper process completed...
authClient: cancel requested, but no helper process
CsScreen dispose
CsScreen finalize

**inxi -F**
System:
  Host: denyhs-Inspiron-3442 Kernel: 5.3.0-40-generic x86_64 bits: 64 
  Desktop: Cinnamon 4.4.8 Distro: Linux Mint 19.3 Tricia 
Machine:
  Type: Portable System: Dell product: Inspiron 3442 v: N/A 
  serial: <root required> 
  Mobo: Dell model: 0C1F3F v: A14 serial: <root required> UEFI: Dell v: A14 
  date: 05/23/2018 
Battery:
  ID-1: BAT0 charge: 30.1 Wh condition: 30.1/41.4 Wh (73%) 
CPU:
  Topology: Dual Core model: Intel Core i5-4210U bits: 64 type: MT MCP 
  L2 cache: 3072 KiB 
  Speed: 1696 MHz min/max: 800/2700 MHz Core speeds (MHz): 1: 1696 2: 1696 
  3: 1696 4: 1696 
Graphics:
  Device-1: Intel Haswell-ULT Integrated Graphics driver: i915 v: kernel 
  Device-2: NVIDIA GF117M [GeForce 610M/710M/810M/820M / GT 
  620M/625M/630M/720M] 
  driver: nvidia v: 340.107 
  Display: x11 server: X.Org 1.20.5 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 1366x768~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: GeForce 820M/PCIe/SSE2 v: 4.4.0 NVIDIA 340.107 
Audio:
  Device-1: Intel Haswell-ULT HD Audio driver: snd_hda_intel 
  Device-2: Intel 8 Series HD Audio driver: snd_hda_intel 
  Sound Server: ALSA v: k5.3.0-40-generic 
Network:
  Device-1: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter 
  driver: ath9k 
  IF: wlp6s0 state: down mac: 68:14:01:cf:62:ef 
  Device-2: Realtek RTL810xE PCI Express Fast Ethernet driver: r8169 
  IF: enp7s0 state: up speed: 100 Mbps duplex: full mac: 20:47:47:fd:37:79 
  Device-3: Atheros type: USB driver: btusb 
Drives:
  Local Storage: total: 2.05 TiB used: 742.31 GiB (35.3%) 
  ID-1: /dev/sda vendor: Western Digital model: WD10JPVX-75JC3T0 
  size: 931.51 GiB 
  ID-2: /dev/sdb vendor: Samsung model: SSD 850 PRO 256GB size: 238.47 GiB 
  ID-3: /dev/sdc type: USB vendor: Samsung model: M3 Portable 
  size: 931.50 GiB 
Partition:
  ID-1: / size: 229.61 GiB used: 55.06 GiB (24.0%) fs: ext4 dev: /dev/sdb3 
  ID-2: swap-1 size: 3.72 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/sdb1 
Sensors:
  System Temperatures: cpu: 63.0 C mobo: 54.0 C gpu: nvidia temp: 59 C 
  Fan Speeds (RPM): cpu: 3345 
Info:
  Processes: 214 Uptime: 7m Memory: 7.68 GiB used: 1.40 GiB (18.3%) 
  Shell: zsh inxi: 3.0.32 

**What gtk theme are you running?** I changed to a Mint theme but it didn't solve the problem

**Comment by mtwebster** [comment]
Does this happen in intel mode or nvidia or both?  Your nvidia driver is pretty old, does the driver manage offer up any of the newer ones?

**Comment by denihs** [comment]
That was the problem! Just to record, I went to the nvidia website and search for my Graphics after that I get the current version and ran `sudo apt-get install --install-recommends nvidia-driver-390`.

Thank you really much for your help!

**Comment by denihs** [comment]
That was the problem! Just to record, I went to the nvidia website and search for my Graphics after that I get the current version and ran `sudo apt-get install --install-recommends nvidia-driver-390`.

Thank you really much for your help!
