### ISSUE TITLE
Dual monitor aspect spanned not working as well

### ISSUE THREAD

**Issue by rafaelribeiroo** [linuxmint/cinnamon-screensaver#336]
My setup is **dual monitor** and recently I install _Linux Mint 19.3_ (with _Cinnamon 4.4.8_) and everything is in the latest version. The problem showed up since the first time I initialize the Mint, the picture aspect "Spanned" conflicts with dual monitor on startup screen. Luckily I'm still able to enter with the password which makes the system start normally.

**Check whats happens below.**

Before log in for the first time

![before login](https://user-images.githubusercontent.com/19275140/80818583-d8b9a380-8ba9-11ea-9916-b9ffd2059671.gif)

**After log in on system works correctly**

![after login](https://user-images.githubusercontent.com/19275140/80818612-e707bf80-8ba9-11ea-8571-bca6f928fad5.gif)

**Comment by mtwebster** [comment]
In the upcoming mint release you'll be able to have the login screen use spanned mode for the wallpaper.

https://github.com/linuxmint/slick-greeter/commit/293fa0d6a596ba9f1e9dd78a3da171fea3110b84

**Comment by rafaelribeiroo** [comment]
Thanks for that, i appreciate this.

**Comment by rafaelribeiroo** [comment]
> In the upcoming mint release you'll be able to have the login screen use spanned mode for the wallpaper.
> 
> [linuxmint/slick-greeter@293fa0d](https://github.com/linuxmint/slick-greeter/commit/293fa0d6a596ba9f1e9dd78a3da171fea3110b84)

I've just install mint 20 and not works yet.
