### ISSUE TITLE
Version 4.6.0 unlocks without passphrase

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-screensaver#338]
```
 * Cinnamon-Screensaver version - 4.6.0
 * Distribution - Alt Linux Sisyphus
 * 64 bit
 ```

**Issue**
cinnamon-screensaver 4.6.0 always unlocks without passphrase - any keyboard press or mouse movement logins me into the system. I tried to bisect that this problem and found that this issue is caused by porting to meson build. 

**Steps to reproduce**
1. Lock screensaver
2. Move mouse or press key on keyboard
3. Screensaver logins into the system

**Expected behaviour**
Screensaver should ask passphrase for the user

**Comment by leigh123linux** [comment]
Works fine here on fedora.
Please post some debug info or this issue will be closed.

```
killall cinnamon-screensaver
cinnamon-screensaver --debug
```

**Comment by mtwebster** [comment]
Is there a 'cinnamon-screensaver' file in /etc/pam.d?

If so, what are its contents?

**Comment by vladimir-didenko** [comment]
@leigh123linux  @mtwebster  I have found root cause - old build system provided special option for configure called "--enable-setres". It was required to make screensaver work on Alt Linux (and probably some other distros). meson build doesn't have it though there is a workaround adding "-DUSE_SETRES" to CFLAGS. But I think explicit option in meson file will be more convenient. What do you think?

**Comment by leigh123linux** [comment]
Try adding this to meson configure

-Dsetres=true

https://github.com/linuxmint/cinnamon-screensaver/blob/master/meson_options.txt#L1

**Comment by vladimir-didenko** [comment]
@leigh123linux Oh, I missed that. So it is not a bug and I am closing bug. Thank you!
