### ISSUE TITLE
Firefox tooltips are remaining in lock screen 

### ISSUE THREAD

**Issue by daschuer** [linuxmint/cinnamon-screensaver#34]
If a tool tip is displayed in Firefox just before the lock screen it remain visible as static text on the lock screen. I think this is a privacy issue and should be fixed. 
Tested with cinnamon-screensaver 2.0.0 and Ubuntu 12.4.

**Comment by theSeppi** [comment]
I confirm, using cinnamon-screensaver 2.4.2 and Firefox 38.0 on Rebecca.

**Comment by kjfergu** [comment]
I can confirm that this bug exists in cinnamon-screensaver 2.6.4

**Comment by leigh123linux** [comment]
Fixed in cinnamon-3.2.x
