### ISSUE TITLE
support launching external binaries such as xscreensaver-gl's glmatrix and add time overlay

### ISSUE THREAD

**Issue by lordbaco** [linuxmint/cinnamon-screensaver#35]
Can you support launching external binaries such as xscreensaver-gl's glmatrix 
and add time as overlay to it ?

It will be nice to have the possibility to display the time with the font/size/color of our choice on top of launching the chosen screensaver.

My current workaround for now :

How to run GLmatrix on Cinnamon
1. sudo killall cinnamon-screensaver gnome-screensaver xscreensaver
2. sudo apt-get -qq -y --purge remove gnome-screensaver
3. sudo apt-get -qq -y install xscreensaver xscreensaver-gl
4. sudo apt-get -qq -y install cinnamon-screensaver
5. sudo mv /usr/bin/cinnamon-screensaver{,.real}
6. sudo mv /usr/bin/cinnamon-screensaver-command{,.real}
7. sudo ln -sf /usr/bin/{xscreensaver,cinnamon-screensaver}
8. sudo ln -sf /usr/bin/{xscreensaver-command,cinnamon-screensaver-command}
9. xscreensaver -no-splash &
10. xscreensaver-command -demo &
11. xscreensaver-command -activate
12. Enjoy CTRL + ALT + L

Thank you in advance.

Guy Baconniere (lordbaco)

**Comment by edmundlaugasson** [comment]
I totally agree what lordbaco wrote. XScreensaver has a lot of great screensavers and there is no point to reimplement them again. Why not just make possible to use them? I would expect the same functionality from cinnamon-screensaver like XScreenaver has.
There would be useful offer configuration feature - would I like to have such lock screen like currently is or would I like to start screensaver right away like XScreensaver does.
I would honestly say - currently I use lordbaco's workaround also myself...

**Comment by mtwebster** [comment]
this has been implemented for some time.. closing.
