### ISSUE TITLE
Any key on-screen keyboard unlocks lock screen

### ISSUE THREAD

**Issue by gunnarre** [linuxmint/cinnamon-screensaver#352]
```
 * Cinnamon-Screensaver version 4.6.0
 * Distribution - Mint 20 Ulyana
 * Geforce GTX 1660 Super (TU116) Driver 455.38-0ubuntu0.20.04.1
 * 64 bit
 ```

**Issue**

Access is given to the desktop if you click any key on the on-screen keyboard on the lock screen. (Does not apply to initial log-in.)

**Steps to reproduce**

* Enable on-screen keyboard (#301).
* Lock screen.
* Press any key on the on-screen keyboard.
* Access is given to the desktop even if you don't enter the password.

**Expected behaviour**

* Screen should not be unlocked without entering the full and correct password and pressing enter.

**Comment by mkaminsky** [comment]
I'm also seeing this with cinnamon-screensaver 4.6.x and with 4.8.1.

To reproduce:
* Lock screen
* Open on-screen keyboard
* Long click on the "u" character to bring up additional characters with diacritics.
* Click "ù"   (just clicking "u" doesn't cause the crash)

At this point, cinnamon-screensaver core dumps, which is why the lock screen disappears.  If I run it in the foreground, I get the following error:
```
(cinnamon-screensaver:209328): Gdk-ERROR **: 11:06:36.031: The program 'cinnamon-screensaver' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadLength (poly request too large or internal Xlib length erro'.
  (Details: serial 7062 error_code 16 request_code 135 (XKEYBOARD) minor_code 9)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

Running gdb on the core dump:
```gdb
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-screensaver/cinnamon-screensaver-pam-helper'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
```

**Comment by gunnarre** [comment]
This appears to be fixed on my system now - both the single key and dialectic issue.
I'm still running cinnamon-screensaver 4.6.0, but graphics driver has been updated to 460.32.03-ubuntu0.20.04.1

**Comment by gunnarre** [comment]
This appears to be fixed on my system now - both the single key and dialectic issue.
I'm still running cinnamon-screensaver 4.6.0, but graphics driver has been updated to 460.32.03-ubuntu0.20.04.1

**Comment by gunnarre** [comment]
Duplicate of #354 which has been fixed.
