### ISSUE TITLE
customization ?

### ISSUE THREAD

**Issue by PowaBanga** [linuxmint/cinnamon-screensaver#360]
Hello everybody,
Here is not an issue, but a question, or a feature request.

I want to know if it is possible to customize the cinnamon screensaver ?

In my case, i just want to change (remove it) the black shadow who is on all the screen. And maybe a way to change the speed  of wallpapers when screen saver is activated..

Does somebody can help me to do that ?

**Comment by sauce420** [comment]
You can customize this kind of stuff from the screensaver and backgrounds apps, just search for them in the start menu. Did this answer your question?

**Comment by PowaBanga** [comment]
"screensaver and backgrounds apps" ??? what are you speaking about exactly ?  I am on Archlinux...

**Comment by sauce420** [comment]
Ahh, sorry I assumed you were on mint. What desktop environment are you using?

**Comment by PowaBanga** [comment]
I am on cinnamon... why ?

**Comment by sauce420** [comment]
I don't know what cinnamon desktop environment ships with but you could try right clicking on the background of the desktop and there should be a menu which you can select from. Choose 'change desktop background and you can choose images and how often the images change from there. If Cinnamon comes with some apps, then try [searching in the start menu](https://youtu.be/mcOqxw9Qufk) where you find apps 'screensaver' and 'backgrounds'.

**Comment by sauce420** [comment]
did this answer your questtion?

**Comment by PowaBanga** [comment]
It's very interessant @sauce420 but no, this not answer to my question. My main is to not have black color opacity above my background picture/photos from desktop when screensaver is activated...

**Comment by sauce420** [comment]
> It's very interessant @sauce420 but no, this not answer to my question. My main is to not have black color opacity above my background picture/photos from desktop when screensaver is activated...

Ah, I don't think this is customizable, but u can open an [issue](https://github.com/linuxmint/cinnamon/issues/new) asking for this to be added

**Comment by PowaBanga** [comment]
ha, I was thinking that it was done by opened it here. So it's done https://github.com/linuxmint/cinnamon/issues/10088

**Comment by sauce420** [comment]
Ok thanks shall we close this issue?

**Comment by PowaBanga** [comment]
If this feature can be done from this repository? Yes i suppose.
