### ISSUE TITLE
How to default to locking the screen on suspend in a distro package

### ISSUE THREAD

**Issue by ericonr** [linuxmint/cinnamon-screensaver#363]
```
 * Cinnamon-Screensaver version 4.8.1
 * Distribution - Void Linux
 ```

**Issue**

I'm not sure I'm asking this in the correct repository. I'm working on updating Cinnamon to the 4.8.x releases for Void Linux, and in my testing I've detected that, by default, the option to lock the screen before suspending the device isn't toggled, meaning that opening the device after suspending it gives me ready access to it, without asking for a password. I consider this behavior slightly surprising, and would like to know if there is some way I can configure the default setting to have that option toggled, so suspend locks the screen and protects a user's desktop.

**Expected behaviour**

By default, without any configuration by the user, suspending the device should also lock their session.

**Comment by JosephMcc** [comment]
The setting you are looking for is this one: https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/data/org.cinnamon.settings-daemon.plugins.power.gschema.xml.in.in#L129

You should be able to override this by using a gsettings-overide. A quick search will tell you how to go about it.

**Comment by ericonr** [comment]
@JosephMcc I see, thanks. Seeing as it's a default which doesn't appear to be configured by distros, do you know why it was set up this way? Maybe I'm missing something.

**Comment by PowaBanga** [comment]
You can use dconf as root to see and/or modify default setting for all user ...

**Comment by ericonr** [comment]
There isn't much to act on right now, though I'd still be interested in knowing the rationale behind the default being not to lock the screen.

Closing issue.
