### ISSUE TITLE
Screensaver does not start if 'start menu' is open

### ISSUE THREAD

**Issue by jlrnr** [linuxmint/cinnamon-screensaver#370]
```
 * Cinnamon-Screensaver version 4.8.1
 * Distribution - Mint 20.1
 * Intel HD Graphics 5500, Toshiba driver: i915 v
 * 64 bit
 ```

**Issue**
If the Start Menu is left open, the screensaver will not start.

**Steps to reproduce**
Open the Start Menu.
Leave the computer until the allotted amount of time the screensaver should start.

**Expected behaviour**
The screen should lock regardless of some 'expected user activity'

**Other information**

**Comment by JosephMcc** [comment]
This has been brought up several times. There are a couple instances that prevent it from working: https://github.com/linuxmint/cinnamon-screensaver/issues/93
