### ISSUE TITLE
Unable to launch cinnamon after update to 5.0.1 because of missing desktop file in LMDE Debbie 

### ISSUE THREAD

**Issue by princepaul** [linuxmint/cinnamon-screensaver#374]
```
 * Cinnamon-Screensaver version (5.0.1)
 * Distribution - (LMDE Debbie)
 * Graphics hardware *and* driver used (Nvidia)
 * 32 or 64 bit (64 bit)
 ```

**Issue**
Was unable to launch cinnamon after building and updating to 5.0.1. Later found that desktop file is required to be named as cinnamon-screensaver.desktop instead of org.cinnamon.ScreenSaver.desktop

**Steps to reproduce**
mint-build cinnamon-screensaver

**Expected behaviour**

**Other information**

**Comment by princepaul** [comment]
Just found this commit.
https://github.com/linuxmint/cinnamon/commit/bfaadebf5f1fa452fc849f6f9a64ea2d10f3cfb1
I think, this will fix it.

**Comment by mtwebster** [comment]
We're tagging a new release with it shortly, sorry about this.
