### ISSUE TITLE
Screen is unlockable via the menu

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-screensaver#385]
```
 * Cinnamon-Screensaver version: 5.0.6
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

There is an inbuilt keyboard shortcut for screenlocking. One can use the 'user' applet to lock the screen. Yet, one cannot lock the screen via the menu applet.

**Steps to reproduce**

1. Open the menu applet and search for 'lock' or 'screen' or similar.
2. Fail to find anything that will lock the screen immediately.

**Expected behaviour**

I expect that the screen be lockable via the menu. For, that function would be useful. More: given the keyboard shortcut and given that the user applet allows one to lock the screen, one expects that function to be present.

**Comment by mtwebster** [comment]
![Screenshot from 2021-07-12 10-46-40](https://user-images.githubusercontent.com/262776/125308339-d222d200-e2fe-11eb-93ee-68e7b5e27d82.png)

**Comment by LinuxOnTheDesktop** [comment]
My mistake. Still, why not make locking accessible via search?
