### ISSUE TITLE
Media info only displayed on second attempt

### ISSUE THREAD

**Issue by SebiderSushi** [linuxmint/cinnamon-screensaver#387]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --version) 5.0.6
 * Distribution - Arch and Mint 20.2
 * Graphics hardware & driver used: Intel HD 3000 with mesa + i915
 * 64 bit
 ```

**Issue**
`cinnamon-screensaver` only recognizes active media and displays media info & controls after locking a second time after media has changed.

**Steps to reproduce**
- Boot up
- Launch e.g. `firefox` or `rhythmbox` and start playing some audio
- Lock the screen
- Move the mouse -> Media Info does not appear
- Unlock the screen
- Lock the screen again
- Move the mouse -> Media Info should be there
- Pause the audio that is playing, it might also be necessary to quit the application in order to force `cinnamon-screensaver` to search for a new audio player
- Start another application and play some audio
- Lock the screen
- Move the mouse -> Media Info does not appear
- Unlock the screen
- Lock the screen again
- Move the mouse -> Media Info should be there

**Expected behaviour**
Media info always appears on lock screen if audio is playing.

**Other information**
First i was only able to reproduce this on arch linux but i just upgraded my linux mint from 20.1 to 20.2 (`cinnamon-screensaver` got updated from 4.8.1 to 5.0.6) and was able to reproduce it there as well. So i downgraded `cinnamon-screensaver` to 4.8.1 on my arch linux and it seems to work fine. This also explains why my other machine running manjaro linux does not show this issue, as `cinnamon-screensaver` is still on 4.8.1 in the manjaro repo.

**Comment by mtwebster** [comment]
This is fixed: https://github.com/linuxmint/cinnamon-screensaver/commit/1748efb91b0eddeebada935f762ab4db211576e6 

Just need to get a new version out.

**Comment by SebiderSushi** [comment]
Thanks!
