### ISSUE TITLE
Hang; screensaver *bypassable*

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/cinnamon-screensaver#390]
```
 * Cinnamon-Screensaver version: 5.0.6
 * Distribution - Mint 20.2
 * Graphics hardware *and* driver used: Intel / Mesa
 * 32 or 64 bit: 64
 ```

**Issue**

After suspend, I discovered that the screensaver would not show the password box. However, switching (via keyboard shortcut) to tty2 worked and indeed I was logged in, as my normal user, on tty2. This seems to be me to be a security bypass (even though switching back to tty7 continued to show the hung lockscreen).

**Steps to reproduce**

Unknown - the hang is intermittent.

**Expected behaviour**

No hang. No bypass.

**Other information**

This is the same issue that I filed as #359. However, given that the newly-discovered bypass, I thought I should open a new issue.

[syslog.txt](https://github.com/linuxmint/cinnamon-screensaver/files/6874519/syslog.txt)
[dmesg.txt](https://github.com/linuxmint/cinnamon-screensaver/files/6874520/dmesg.txt)

Host: 20KH001UKP ThinkPad X1 Carbon 6th 
Kernel: 5.8.0-63-generic 
Uptime: 6 mins 
Packages: 3338 (dpkg), 7 (flatpak) 
Shell: bash 5.0.17 
Resolution: 2560x1440 @ 60.01Hz 
DE: Cinnamon 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark (Mint-Y-Dark) 
Theme: Mint-Y-Dark [GTK2/3] 
Icons: Paper [GTK2/3] 
Terminal: xfce4-terminal 
Terminal Font: InconsolataGo 12 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: Intel UHD Graphics 620 
Memory: 2298MiB / 15902MiB 
Disk (/dev/nvme0n1p4): 17G / 40G (46%) 
Disk (/dev/nvme0n1p2): 165G / 405G (43%) 
Disk (udev): 0 / 7.8G (0%)

**Comment by LinuxOnTheDesktop** [comment]
Judging by the time shown on the frozen screensaver, the hang occurred some time around Jul 25 Jul 25 06:00.

**Comment by mtwebster** [comment]
This is working as expected - you shouldn't keep your tty logged in if this is a concern. Also, you can run `cinnamon-unlock-desktop` from there when you get this freeze to get your desktop back.

**Comment by LinuxOnTheDesktop** [comment]
> '[Y]ou shouldn't keep your tty logged in if this is a concern'

Do you mean that I should not have opened a tty before the screensaver hang occured? To my knowledge, I had _not_ opened a tty before the screensaver hang occured. But perhaps I had (and if I had done so accidentally, then cf. https://github.com/linuxmint/cinnamon/issues/10208.).

> [Y]ou can run cinnamon-unlock-desktop from there when you get this freeze to get your desktop back.

Well, that is a workaround for the bug. So, thank you.

**Comment by LinuxOnTheDesktop** [comment]
- Just now I experienced the same hang and this time I was prompted on tty to login. So _that is some evidence that one must indeed be logged in already via tty before one can move from a hung screensaver to a logged-in tty session._

- On the hang itself, cf.: #371; #383; #https://github.com/linuxmint/cinnamon/issues/10240. I infer from the existence of those other three reports - together with mine - that there is a serious problem in this area.

**Comment by mtwebster** [comment]
You can *always* access a tty, whatever state your screensaver or desktop is in (with the exception of some hard system freeze). There's no relationship here. Consider a tty a backdoor to your system that nothing in your session knows about.

Those issues will remain open until I have some way to reproduce this problem.

**Comment by LinuxOnTheDesktop** [comment]
Thank you for the information.

Perhaps I was unclear. What really worried me, was that I was _logged into_ the tty. Still, I take it that the reason for that logged-in state was that I had logged in - to the tty - already, i.e. during the same user session.

Yet, suppose: a user logs in a tty and does not log out of it; the same user switches to the desktop; and then the screensaver starts. In that case, the screensaver is easily circumventable, making one wonder what the point of the screenlocker ('locker') is. So: tty's cannot be disabled? And tty sessions cannot automatically be logged out? At the least, can the screenlocker - before locking - not display a warning about any logged-in tty?

**Comment by LinuxOnTheDesktop** [comment]
Anything I can do to help fix this problem? Having to switch to a tty and run the workaround command and then switch back to the desktop is - even though I put the workaround command in a script - a pain.

**Comment by potassium-chloride** [comment]
1)The tty capability is not a security issue because you need a login:password pair to execute commands or other actions. If you forgot to log out, this is the **user**'s problem, not a bug.

Let's look at the situation: you logged into your linux server via SSH, minimized the terminal window and left for tea, someone saw the minimized window and executed some bad commands while you were drinking tea. Why did this happen? Because the user did not log out of the SSH client. The software was working correctly and normally.

2)Skip to tty is useful for forcibly fixing some GUI problems without restarting the X-server or rebooting the OS or another cases.
