### ISSUE TITLE
Notifications are lost after unlocking screensaver

### ISSUE THREAD

**Issue by SebastJava** [linuxmint/cinnamon-screensaver#391]
```
 • cinnamon-screensaver 5.0.6
 • Mint 20.2
 • 64 bit
 • Graphics:  Device-1: Intel 2nd Generation Core Processor Family Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.9 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2000 (SNB GT1) v: 3.3 Mesa 20.2.6
 ```

**Issue**
I locked my screen. Later, i get this small symbol on top-right showing i got some notification. So, i unlock to see what is this notification about, but my notification got cleared.

**Steps to reproduce**
(What follows is just for testing purposes. It would be more relevant if you could manage to receive some notification about some email...)
1. Set the timer countdown to 10s. Wait. (Gnome-clocks used for this test)
2. Watch the system tray: you got a new notification. Click on this notification so you will know what it is about. This works fine.
3. Set the timer countdown to 10s.
4. Lock screen. Wait.
5. There is a little symbol on top-right of your locked screen showing you got a new notification.
6. Unlock the screen to take a look at this new notification: it got cleared, you can't be informed.

https://user-images.githubusercontent.com/31940713/127037463-734bd29f-d081-4317-a316-6f7a17f548f7.mp4

**Expected behaviour**
I would expect to be able to learn more about this notification when i unlock my screen. But it got cleared.

**Other information**
I don't know where this problem really comes from. Is it something wrong with cinnamon-screensaver or notification(a)cinnamon.org?

**Comment by SebastJava** [comment]
Oops. It looks like this is probably not a problem with the screensaver, but with notification(a)cinnamon.org.

These notifications can be cleared unexpectedly. For example, just opening and closing Nemo causes this notification to be lost.

**Comment by SebastJava** [comment]
P.S.: Where can i report problems with this notification@cinnamon.org ?

**Comment by SebastJava** [comment]
Or, maybe these Gnome-clocks notifications are a special kind of notifications that gets cleared easily?

So, there would be no problem at all? Unsure...

**Comment by mtwebster** [comment]
Applications can send 'transient' notifications - usually these are only momentarily relevant (like the track changing in a music player) and aren't kept around. Apps also have the ability to 'withdraw' notifications for any reason, and replace ones they sent previously.

Cinnamon-screensaver filters out ones marked as transient, but I think it an app isn't using that mechanism (and is maybe using its own timer) or is withdrawing it at some point, the screensaver won't notice that. This is a bit of a muddy area unfortunately as far as what behavior is expected vs what various implementations do.
