### ISSUE TITLE
Screensaver Crash

### ISSUE THREAD

**Issue by my-name-was-not-available** [linuxmint/cinnamon-screensaver#395]
```
 * Cinnamon-Screensaver version - (5.0.6)
 * Distribution - (Linux Mint 20.2 Cinnamon)
 * Graphics hardware *and* driver used - (Intel Core  i5-10210U (integrated GPU), OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 21.0.3 )
 * 32 or 64 bit - (64bit)
 ```

**Issue**
Screensaver crashes after ~ 1 hour

**Steps to reproduce**
- Lock the screen and wait
    → after some while, monitor turns off due to inactivity
- move mouse to reactivate monitor

**Expected behaviour**
screen is black and shows crash message

**Other information**
Happens every time after some while, not randomly.
System: Intel NUC i5-10210U, 16GB RAM, 500GB NVME SSD

**Comment by EvilSupahFly** [comment]
Looks like your issue is the same as #392.
