### ISSUE TITLE
Dual monitor display: one monitor 'awakening' when in lock/sleep

### ISSUE THREAD

**Issue by mmcelroy75** [linuxmint/cinnamon-screensaver#409]
```
 * Cinnamon-Screensaver version (cinnamon-screensaver --5.4.0-1)
 * Distribution - (ArcoLInux/Arch)
 * Graphics hardware *and* driver used - Advanced Micro Devices, Inc. [AMD/ATI] Cezanne
 * 64 bit
 ```

**Issue**

When computer in dual monitor setup goes to sleep, only one monitor screen (primary) is dimmed with the floating clock. The other screen remains open and undimmed as if in use, it cannot be accessed and mouse clicks don't respond (which is good).  When actively locking, both monitors do go dim. It's only when the system sleeps on its own.

**Steps to reproduce**

Let computer sit and go to sleep.

**Expected behaviour**

Both screens should be dimmed. 

**EDIT**

This issue is happening after the computer has been asleep/locked for a while. The monitor seems to "cycle" at some point during the sleep and one monitor will un-dim and wake up. It still cannot be accessed by mouse click though. Computer entering sleep or being locked manually with Ctrl-Alt-L, for example, works as intended, however after the computer cycles through, the one monitor will awaken and display the contents of the workspace as it were before it locked.

**Comment by xhpohanka** [comment]
I have described similar issue here:

https://github.com/linuxmint/cinnamon/issues/10942

**Comment by lbr38** [comment]
> Hi, can you try 5.4.1? It has a _lot_ of changes that try to address a number of issues, including this one.
> 
> Thanks

Hi
I got cinnamon-screensaver **5.4.2** and have similar issue.

**Comment by mtwebster** [comment]
Hi I think I have this fixed - if you'd like, could you try the packages here:
https://github.com/linuxmint/cinnamon-screensaver/releases/tag/master.mint21

Otherwise the fix will be in the next release.

Download packages.tar.gz, extract them, and open a terminal at their location, then run:
```
sudo dpkg -i *.deb
```
(Don't try to just double-click on them to install - they need to be installed all at once).
 

Thanks!

**Comment by Redsandro** [comment]
Thank you @mtwebster :+1: 

I'll just mention the other bug for the linkback and bookkeeping reasons: #204

**Comment by S3DEV** [comment]
> Hi I think I have this fixed - if you'd like, could you try the packages here: https://github.com/linuxmint/cinnamon-screensaver/releases/tag/master.mint21
> 
> Otherwise the fix will be in the next release.
> 
> Download packages.tar.gz, extract them, and open a terminal at their location, then run:
> 
> ```
> sudo dpkg -i *.deb
> ```
> 
> (Don't try to just double-click on them to install - they need to be installed all at once).
> 
> If you have any trouble, the Update Manager will re-install the official version for you. (If it does work, you'll want to blacklist cinnamon-screensaver or just uncheck it when updating).
> 
> Thanks!

Thank you for working on this.

Issue still exists.

To reproduce:
- Plug in HDMI to second monitor
- Lock screen
- Unplug HDMI
- Let screens calibrate
- Plug HDMI back in
- Screens are either revealed, or the login screen only partially appears on the (second) monitor, but login field is no visible.

Thank you for your hard work!
