### ISSUE TITLE
cinnamon-screensaver crashes and lock screen unlocks on its own

### ISSUE THREAD

**Issue by KyleFromKitware** [linuxmint/cinnamon-screensaver#417]
```
 * cinnamon-screensaver 4.6.0
 * Distribution - Mint 20
 * Graphics hardware *and* driver used - NVIDIA Corporation GM107GLM [Quadro M1200 Mobile] (rev a2)
 * 64 bit
 ```

**Issue**

I've recently started seeing an issue where, when I lock the screen and walk away from my laptop, after some period of time `cinnamon-screensaver` will crash and unlock the screen. When I come back, the screen is unlocked as if I had never locked it, and I see the following in `dmesg`:

```
[ 1138.269741] cinnamon-screen[3894]: segfault at 6174617a ip 00007f7551293160 sp 00007ffec53e10f8 error 4 in libgobject-2.0.so.0.6400.6[7f7551265000+36000]
```

And I am no longer able to lock the screen again.

Restarting `lightdm` manually fixes the issue and makes it so I can lock the screen again, but having the screen randomly unlock when I'm away from my computer is a massive security issue.

**Steps to reproduce**

1. Lock screen
2. Wait for `cinnamon-screensaver` to crash

**Expected behaviour**

`cinnamon-screensaver` doesn't crash and the screen remains locked.

**Comment by KyleFromKitware** [comment]
Not sure if this is related to #392?

**Comment by mtwebster** [comment]
Quite a bit has changed since the version you're running - I'd suggest trying the latest version.

**Comment by KyleFromKitware** [comment]
Thanks. I'm running Linux Mint 20, is there a way to upgrade `cinnamon-screensaver` without upgrading the Linux Mint version?
