### ISSUE TITLE
Crash when muffin is unavailable

### ISSUE THREAD

**Issue by SebiderSushi** [linuxmint/cinnamon-screensaver#421]
As far as i understand the code, version 5.6.0 tries to check with muffin to see if fractional scaling should be used. However, if muffin is not running the code tries to access an unassigned variable. It looks like `read_current_state()` is supposed return [at the end of the `except` block.](https://github.com/linuxmint/cinnamon-screensaver/blob/020b33ff3b386cc42fbad972f61ee836ad6fbaea/src/dbusdepot/muffinClient.py#L55)

This is presumably a non-occuring issue when `cinnamon-screensaver` is used together with `cinnamon`, as is supported.
I encountered this crash because i am using `cinnamon-screensaver` with Xfce and thus do not use muffin. Recompiling with a return statement at the suggested position fixes the crash and the screensaver activates successfully.

**Comment by mtwebster** [comment]
Thanks for the catch

**Comment by SebiderSushi** [comment]
Thanks for the immediate fix!
