### ISSUE TITLE
Can see windows on desktop before lockscreen appears when monitors turn on

### ISSUE THREAD

**Issue by mrmelon54** [linuxmint/cinnamon-screensaver#437]
### Distribution

Linux Mint 21.2 Cinnamon

### Package version

5.8.4

### Graphics hardware in use

NVIDIA GeForce RTX 3070 TI

### Frequency

Always

### Bug description

I can see the windows on my desktop before the lockscreen appears when waking my pc after the monitors turn off

### Steps to reproduce

Lock pc, wait for screen to go off and wake pc by shaking mouse, keyboard or other methods.

### Expected behavior

The lockscreen should show up and not display any windows I have open on my desktop

### Additional information

The windows also more around when waking a multiple monitor setup. e.g. I would have an IDE/browser open on one monitor and when waking up I would see it on a different monitor, then the lockscreen would appear and I would login. The window would then stay on the exact place I saw it before the lockscreen appeared.

**Comment by MrMelon54** [comment]
Related to #436
