### ISSUE TITLE
crtl + alt + f1 does not enable me to log in

### ISSUE THREAD

**Issue by rdfuhr** [linuxmint/cinnamon-screensaver#457]
### Distribution

22

### Package version

6.2.0

### Graphics hardware in use

unknown

### Frequency

Only occasionally

### Bug description

When I opened my laptop after it had been in sleep mode, I saw an error message about unable to launch the screensaver.  I was given a series of steps to follow, starting with invoking ctrl + alt + F1 which should have enabled me to log in.  But ctrl + alt + F1 did nothing. Moreover, I could not power down my laptop by holding down the power button.  Fortunately by invoking ssh to my Linux Mint machine from a different computer, I was able to invoke shutdown --reboot.

### Steps to reproduce

Just sleep your Linux Mint computer by closing the lid.  Are you able to log in when you open the lid?

### Expected behavior

You should be able to log in to your Linux Mint computer when you open the lid.

**Comment by leigh123linux** [comment]
Report the issue against the kernel.
