### ISSUE TITLE
monitor not turning off

### ISSUE THREAD

**Issue by ghost** [linuxmint/cinnamon-screensaver#46]
have this set to turn monitor off after 5mins but it only goes to my lockscreen

strangely enough it does sometimes yet very rarely turn my monitor off

linux mint 16 x64 cinnamon with cinnamon-screensaver 2.0.3

**Comment by PeterHorvathScreamingBox** [comment]
It seems it is still an unsupported feature of the cinnamon-screensaver. Furthermore, also scripting the cinnamon-screensaver of changing it to another screensaver is still unsupported.

**Comment by PeterHorvathScreamingBox** [comment]
Currently you can turn the monitor off automatically in the energy options. It is an independent feature as the currently used screensaver/locker.

**Comment by HorvathAkosPeter** [comment]
Currently, you can automatically turn off the monitor after inactivity in the settings -> energy options. It is an independent setting as the screensaver/locker.

**Comment by leigh123linux** [comment]
Cinamon-screensaver never controlled monitor power off!
If I remember right the DPMS code is in 'cinnamon-settings-daemon power plugin' and cinnamon-desktop.
I have a HIDPI DP monitor and DPMS is working fine.

**Comment by jerkey** [comment]
this should not be closed, it's still a problem.  Linux Mint 17.3 Rosa, System Settings/Power Management/Power Options/Turn off the screen when inactive for is set to "10 minutes"
$ xset q | grep Off
  Standby: 0    Suspend: 0    Off: 0

if i do $ xset dpms 0 0 600
it will work for a while and then magically change back to 0 0 0, even though /usr/bin/xset is not being executed.
What is going on?  something is overriding dpms and turning it off.

**Comment by unxed** [comment]
maybe it should be reported here:
https://github.com/linuxmint/cinnamon-settings-daemon
?

btw, having the same issue with mate:
https://github.com/mate-desktop/mate-settings-daemon/issues/194
