### ISSUE TITLE
When screen goes off locking doesn't occur

### ISSUE THREAD

**Issue by akstrfn** [linuxmint/cinnamon-screensaver#57]
When screensaver is off and in screen locker "Lock the computer when the screen turns off" is on cinnamon doesn't lock the screen. 
I can easily reproduce problem if in "Power Management" I set "Start the screensaver when inactive for" to "Never". I presume this is not intentional behavior.

I am using LM17.

**Comment by Vahan86** [comment]
@akstrfn, is this still an issue for you in Cinnamon 3?

**Comment by akstrfn** [comment]
@Vahan86 I can't confirm, since I don't use cinnamon anymore.
