### ISSUE TITLE
cinnamon-screensaver : support xscreensaver-gl binaries such as glmatrix

### ISSUE THREAD

**Issue by slmingol** [linuxmint/cinnamon-screensaver#64]
This [ticket was added to the main Cinnamon issue tracker and subsequently closed since](https://github.com/linuxmint/Cinnamon/issues/2531) it was the wrong venue, so moving it over here on the off chance that it might get implemented.

> lordbaco commented on Oct 24, 2013
> Can you add support for xscreensaver-gl binaries such as glmatrix ?

> On top of that it will be nice to have the possibility to display the time with the font/size/color of our  choice on top of the chosen screensaver.

> #### WORKAROUND

> How to run GLmatrix on Cinnamon by Guy Baconniere (lordbaco)

> #### INSTALL
> 0. sudo killall cinnamon-screensaver gnome-screensaver xscreensaver
> 1. sudo apt-get -qq -y --purge remove gnome-screensaver
> 2. sudo apt-get -qq -y install xscreensaver xscreensaver-gl
> 3. sudo apt-get -qq -y install cinnamon-screensaver
> 4. sudo mv /usr/bin/cinnamon-screensaver{,.real}
> 5. sudo mv /usr/bin/cinnamon-screensaver-command{,.real}
> 6. sudo ln -sf /usr/bin/{xscreensaver,cinnamon-screensaver}
> 7. sudo ln -sf /usr/bin/{xscreensaver-command,cinnamon-screensaver-command}
> 8. xscreensaver -no-splash &
> 9. xscreensaver-command -demo &
> 10. xscreensaver-command -activate
> 11. Enjoy CTRL + ALT + L

**Comment by monsta** [comment]
Looks same as https://github.com/linuxmint/cinnamon-screensaver/issues/35
