### ISSUE TITLE
Lots of programs launch gnome-screensaver if it's installed, leading to two screensavers

### ISSUE THREAD

**Issue by marga-google** [linuxmint/cinnamon-screensaver#65]
It was already reported in the past that using cinnamon in Ubuntu Trusty caused double screensavers.  This was worked around by blacklisting the indicator that was the one causing this on session start.

The problem is that this is not the only program that causes double screensaver.  Any program accessing dbus and asking for the org.gnome.ScreenSaver object will cause this.

For example, xdg-screensaver access it and causes this:

$ ps ax | grep screensaver
27440 ?        Sl     0:00 cinnamon-screensaver
31103 pts/10   S+     0:00 grep --color=auto screensaver
$ xdg-screensaver status
enabled
$ ps ax | grep screensaver
27440 ?        Sl     0:00 cinnamon-screensaver
31134 ?        Sl     0:00 /usr/bin/gnome-screensaver --no-daemon
31143 pts/10   S+     0:00 grep --color=auto screensaver

Pidgin uses it for away notification (there's a Feature Request about this in this bug tracker as well). And I'm sure many other programs use it as well.

It would be great if cinnamon-screensaver would also provide org.gnome.ScreenSaver or at least org.freedesktop.ScreenSaver (the one provided by KScreenSaver), so that we don't need to go chasing every possible command to use org.cinnamon.ScreenSaver as well as the other two.

**Comment by lestcape** [comment]
I think that will be more problematic a direct call to gnome-screensaver, and will be necessary use the LD_PRELOAD trick...

**Comment by ACinnamonUserInUK** [comment]
I have a related problem. It's that when previewing screensavers, sometimes - not always - one seems to get superimposed on the other. One can begin to see that happening here (problems with my screengrabber are getting in the way of capturing a more developed version of the problem):

![image](https://cloud.githubusercontent.com/assets/9998846/21443230/50bb1678-c89b-11e6-8f64-a84844b92f10.png)

**Comment by mtwebster** [comment]
This problem has been resolved for some time - cinnamon-screensaver kills off anything else blocking it from registering properly:

af763e6377468caf08f9d4e16a1b37c967b4e0af
2c242aea9238f823c4b20f938a5961feffd9bcd1

XScreensaver plugins have been gone for a while also.
