### ISSUE TITLE
cinnamon-screensaver 2.4.0 fade to black is gone

### ISSUE THREAD

**Issue by sb56637** [linuxmint/cinnamon-screensaver#76]
Hello, one of my favorite features of cinnamon-screensaver was the ~5 sec. fade to black before the screen turns off. This seems to be broken in cinnamon-screensaver 2.4.0. Any chance of restoring this extremely useful functionality? Thanks a lot!

**Comment by DrPandemic** [comment]
I had this problem in the past, but currently I'm on the same Arch laptop with cinnamon 2.4.6 and the fade to black is present

**Comment by sb56637** [comment]
I don't get it. Is there some kind of hidden dconf setting for this?

**Comment by mtwebster** [comment]
Do you have both "Power Management->Turn off the screen when inactive for" and "Screen Locker->Lock the computer when inactive" set?  Try inverting them or disabling one?  One triggers a blank screen, the other the wall clock display.  (Yes this is ridiculously confusing)

**Comment by sb56637** [comment]
@mtwebster Ah, interesting. Thanks for suggesting this. I found that when I set the "Screen Locker" > "Lock the computer when inactive" time to less than my "Power Management" > "Turn off the screen when inactive for" time, the fade works. But unfortunately this is not the configuration that I want. So it appears to be more of a semantic issue with conflicting settings in Cinnamon 2.4 rather than a technical bug. I'm attaching screenshots of the way I want my Power / Lock settings, but with the addition of screen fade to black.

![screenshot from 2015-02-10 11 47 56](https://cloud.githubusercontent.com/assets/2692138/6131904/366867fe-b11d-11e4-816f-4ad9d12fec1e.png)
![screenshot from 2015-02-10 12 01 25](https://cloud.githubusercontent.com/assets/2692138/6131903/363a5c56-b11d-11e4-8cb3-d957725063e9.png)

**Comment by sb56637** [comment]
Any update on this or chance of getting it fixed? Thanks!

**Comment by sb56637** [comment]
OK, it looks like this is mainly a semantics error. (See https://github.com/linuxmint/cinnamon-screensaver/issues/103)

I confirm that with Cinnamon 2.6 my screen fades to black immediately before powering off after 5 minutes of inactivity.

![screenshot from 2015-08-27 09 15 14](https://cloud.githubusercontent.com/assets/2692138/9522861/a8d08cf2-4c9c-11e5-834b-5cd6eb8dcf85.png)

**Comment by sb56637** [comment]
closed
