### ISSUE TITLE
Feature Request: notifiations on screensaver 

### ISSUE THREAD

**Issue by fedoriano** [linuxmint/cinnamon-screensaver#77]
I think  would be useful  add the option to show certain notifications on the lock screen of cinnamon, for example the song that is playing, update alerts, notifications of pidgin and thunderbird, etc
something like gnome-screensaver

**Comment by Ipswitch** [comment]
There is a pull request pending that would change the program to re-read the default message when the clock updates.  That would allow you to populate the default message with notifications while the screen saver is running.  This is easier than trying to allow cinnamon-screensaver access to a multitude of programs.  You would need to populate the default message with values you want displayed.

**Comment by leigh123linux** [comment]
I believe these issues are addressed in cinnamon-screensaver-3.2.x., please confirm.

**Comment by JosephMcc** [comment]
Even if not I don't think you're going to get more than you do now. This was talked about and I think it was decided that we didn't want to show show more than the number of notifications.
