### ISSUE TITLE
Looks different on HiDPI screen

### ISSUE THREAD

**Issue by pkern** [linuxmint/cinnamon-screensaver#83]
On a 3840x2160 HiDPI screen cinnamon-screensaver renders its login prompt too large.

![cinnamon-screensaver-hidpi-lock](https://cloud.githubusercontent.com/assets/42176/6579537/2ef42160-c721-11e4-94e1-becf561a2a9f.jpg)

**Comment by leigh123linux** [comment]
Fixed in cinnamon-screensaver-3.2.x
