### ISSUE TITLE
Black bar in lockscreen. (2.4.6)

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon-screensaver#84]
#56 is still an issue in cinnamon 2.4.6. (Regression?)
![Black bar image](http://i.imgur.com/5eS1eAx.jpg)
Maybe this [this thread](https://bbs.archlinux.org/viewtopic.php?id=184664) helps. It contains a "patch" and is marked as solved. I did not test this.

**Comment by shanemikel** [comment]
Using cinnamon-screensaver 2.4.1-1 on archlinux, I had this problem.  Following the recommendation of changing:
<code>
GdkColor transparentColor = { 0, 0, 0, 0 };
</code>
to:
<code>
GdkColor transparentColor = { 0, 0, 0, 1 };
</code>
didn't work for me, but changing it to:
<code>
GdkColor transparentColor = { 1, 1, 1, 1 };
</code>
did for some reason... go figure.

**Comment by ManuelSchneid3r** [comment]
If I may ask, what exactly is this doing?

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon-screensaver/commit/bfb41fb734c6c2525b9cee4b4c9f13ef7fa69305
