### ISSUE TITLE
screensaver doesnt respect multimonitor and wallpaper setting

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/cinnamon-screensaver#92]
i have a multi-monitor-setting with a stretched wallpaper.

the main monitor is normal in the center,
the second monitor is on the left, but rotated.

the wallpaper is setted for stretching so the entire wallpaper is visible on both monitors combined.

but when i lock the session and go to the cinnamon-screensaver place,
it does show the image on both monitors but on each of them extra (and its not stretched)

**Comment by thorsummoner** [comment]
The file that gnome and cinnamon render as your background is different from the one that renders on the lock screen. I Too see this as a flaw in cinnamon.

The lock screen pulls, I think the first file in this directory: `~/.cache/wallpaper` and renders it on both screens with a dim effect.

I'm not sure where the desktop image is sourced from.

**Comment by JosephMcc** [comment]
https://github.com/linuxmint/cinnamon-screensaver/issues/127
