### ISSUE TITLE
[3.2.0]Screen is not locked if a menu is open

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/cinnamon-screensaver#93]
I guess the problem is rather the grab, than the tooltip it self.

**Comment by Hanmac** [comment]
i dont know if its the same problem or a similar one, but for me its when the tooltip is shown like from Firefox tablist that the screen is locked but the tooltip is still shown (the mouse didnt move)

**Comment by ManuelSchneid3r** [comment]
Sorry for posting that late, I was in vaccations meanwhile. I meant menus not tooltips, i.e. the dropdown menues in an application, the menues in the systray or simply the context menu.

**Comment by kehugter** [comment]
Yup, noticed it too. A concrete example: having [lestcape's Configurable-Menu](https://github.com/lestcape/Configurable-Menu) open blocks the screensaver.

Mint 17.2
cinnamon-screensaver 2.6.4

**Comment by marga-debian** [comment]
This is a very old known issue related to how X11 (the graphical stack used on Linux) works.  This is part of the design of X11 and thus this is not something that ANY desktop environment can fix (in other words, all desktop environment and screensavers are affected by this).

This will be solved when we move to Wayland for the graphical stack (maybe a couple of years in the future).

**Comment by leigh123linux** [comment]
Issue is still present in c-s-3.2.x

**Comment by JosephMcc** [comment]
I'll mark this as a bug but I'm not sure if it can actually be fixed. A menu essentially "takes over" until you close it.

**Comment by feren** [comment]
Ironically, in the Vivaldi menu, the lockscreen appears when the menu is closed, also, I can confirm that it may be fixable given KDE's lockscreen locks just fine from my testing (5.X)

**Comment by cinnamoner** [comment]
> I can confirm that it may be fixable given KDE's lockscreen locks just fine from my testing in similar circumstances (5.X)

@feren Correct.

**Comment by Cos-mo** [comment]
The bug still exists in Mint 18.2 beta Cinnamon 64 bit. Tested by opening the main menu from the panel.

**Comment by JosephMcc** [comment]
There is some debate internally on how much of a bug this really is. Even if we somehow fix it for open Cinnamon menus it will still happen for menus from your applications and that is out of our control.

**Comment by vishwin** [comment]
Does xdo in the referenced commit refer to [xdotool](https://www.semicomplete.com/projects/xdotool/)? If so, they have a pkgconfig file, which can work more reliably. `cc.find_library()` is not finding the library despite being installed.

**Comment by mtwebster** [comment]
Weird, what distro? With libxdo-dev installed nothing came up in `pkg-config --list-all`, but find_library() did. I could have it check both methods I suppose.

**Comment by vishwin** [comment]
FreeBSD ports. We separate base system and third-party/ports as separate prefixes (this falls into the latter), and `cc`, without further qualifications, tends to not look outside `/` and `/usr`. Side note, this is also why `X11/extensions/Xrandr.h` and `X11/extensions/shape.h` don't get detected despite being installed.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/cinnamon-screensaver/commit/7673a6c136ab66e3670919460a87f8887f0ba9b7

**Comment by mtwebster** [comment]
I'm going to close this. 4ae9f1da8 probably doesn't cover every single instance where a server grab might prevent the screensaver from starting, but I think it will come close.

If someone experiences the issue thru some other type of popup we can revisit this.

This fix is included in the most recent release (5.4.1)
